import convexCascadingDelete from "@00akshatsinha00/convex-cascading-delete/convex.config";
import actionCache from "@convex-dev/action-cache/convex.config";
import aggregate from "@convex-dev/aggregate/convex.config";
import crons from "@convex-dev/crons/convex.config";
import geospatial from "@convex-dev/geospatial/convex.config";
import launchdarkly from "@convex-dev/launchdarkly/convex.config";
import migrations from "@convex-dev/migrations/convex.config";
import polar from "@convex-dev/polar/convex.config";
import presence from "@convex-dev/presence/convex.config";
import rateLimiter from "@convex-dev/rate-limiter/convex.config";
import stripe from "@convex-dev/stripe/convex.config.js";
import twilio from "@convex-dev/twilio/convex.config";
import workflow from "@convex-dev/workflow/convex.config";
import workOSAuthKit from "@convex-dev/workos-authkit/convex.config";
import convexFilesControl from "@gilhrpenner/convex-files-control/convex.config";
import debouncer from "@ikhrustalev/convex-debouncer/convex.config";
import { defineApp } from "convex/server";
import apiKeys from "convex-api-keys/convex.config.js";
import apiTokens from "convex-api-tokens/convex.config";
import auditLog from "convex-audit-log/convex.config.js";
import fs from "convex-fs/convex.config.js";
import timeline from "convex-timeline/convex.config.js";
import tracer from "convex-tracer/convex.config";

const app = defineApp();
app.use(workOSAuthKit);
app.use(actionCache);
app.use(convexFilesControl);
app.use(debouncer);
app.use(rateLimiter);
app.use(presence);
app.use(migrations);
app.use(aggregate);
app.use(geospatial);
app.use(crons);
app.use(twilio);
app.use(launchdarkly);
app.use(polar);
app.use(convexCascadingDelete);
app.use(stripe);
app.use(apiKeys);
app.use(apiTokens);
app.use(auditLog);
app.use(fs);
app.use(timeline);
app.use(tracer);
app.use(workflow);

export default app;
