/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as E2eSwitchOrgRouteImport } from './routes/e2e/switch-org'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoConvexWorkflowRouteImport } from './routes/demo/convex-workflow'
import { Route as DemoConvexTriggersRouteImport } from './routes/demo/convex-triggers'
import { Route as DemoConvexTracerRouteImport } from './routes/demo/convex-tracer'
import { Route as DemoConvexTimelineRouteImport } from './routes/demo/convex-timeline'
import { Route as DemoConvexRateLimiterRouteImport } from './routes/demo/convex-rate-limiter'
import { Route as DemoConvexPresenceRouteImport } from './routes/demo/convex-presence'
import { Route as DemoConvexMigrationsRouteImport } from './routes/demo/convex-migrations'
import { Route as DemoConvexGeospatialRouteImport } from './routes/demo/convex-geospatial'
import { Route as DemoConvexFluentRouteImport } from './routes/demo/convex-fluent'
import { Route as DemoConvexFileManagementRouteImport } from './routes/demo/convex-file-management'
import { Route as DemoConvexDebouncerRouteImport } from './routes/demo/convex-debouncer'
import { Route as DemoConvexCronsRouteImport } from './routes/demo/convex-crons'
import { Route as DemoConvexCascadingDeleteRouteImport } from './routes/demo/convex-cascading-delete'
import { Route as DemoConvexAuditLogRouteImport } from './routes/demo/convex-audit-log'
import { Route as DemoConvexApiCredentialsRouteImport } from './routes/demo/convex-api-credentials'
import { Route as DemoConvexAggregateRouteImport } from './routes/demo/convex-aggregate'
import { Route as DemoConvexActionCacheRouteImport } from './routes/demo/convex-action-cache'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eSwitchOrgRoute = E2eSwitchOrgRouteImport.update({
  id: '/e2e/switch-org',
  path: '/e2e/switch-org',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexWorkflowRoute = DemoConvexWorkflowRouteImport.update({
  id: '/demo/convex-workflow',
  path: '/demo/convex-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexTriggersRoute = DemoConvexTriggersRouteImport.update({
  id: '/demo/convex-triggers',
  path: '/demo/convex-triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexTracerRoute = DemoConvexTracerRouteImport.update({
  id: '/demo/convex-tracer',
  path: '/demo/convex-tracer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexTimelineRoute = DemoConvexTimelineRouteImport.update({
  id: '/demo/convex-timeline',
  path: '/demo/convex-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRateLimiterRoute = DemoConvexRateLimiterRouteImport.update({
  id: '/demo/convex-rate-limiter',
  path: '/demo/convex-rate-limiter',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexPresenceRoute = DemoConvexPresenceRouteImport.update({
  id: '/demo/convex-presence',
  path: '/demo/convex-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexMigrationsRoute = DemoConvexMigrationsRouteImport.update({
  id: '/demo/convex-migrations',
  path: '/demo/convex-migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexGeospatialRoute = DemoConvexGeospatialRouteImport.update({
  id: '/demo/convex-geospatial',
  path: '/demo/convex-geospatial',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexFluentRoute = DemoConvexFluentRouteImport.update({
  id: '/demo/convex-fluent',
  path: '/demo/convex-fluent',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexFileManagementRoute =
  DemoConvexFileManagementRouteImport.update({
    id: '/demo/convex-file-management',
    path: '/demo/convex-file-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoConvexDebouncerRoute = DemoConvexDebouncerRouteImport.update({
  id: '/demo/convex-debouncer',
  path: '/demo/convex-debouncer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexCronsRoute = DemoConvexCronsRouteImport.update({
  id: '/demo/convex-crons',
  path: '/demo/convex-crons',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexCascadingDeleteRoute =
  DemoConvexCascadingDeleteRouteImport.update({
    id: '/demo/convex-cascading-delete',
    path: '/demo/convex-cascading-delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoConvexAuditLogRoute = DemoConvexAuditLogRouteImport.update({
  id: '/demo/convex-audit-log',
  path: '/demo/convex-audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexApiCredentialsRoute =
  DemoConvexApiCredentialsRouteImport.update({
    id: '/demo/convex-api-credentials',
    path: '/demo/convex-api-credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoConvexAggregateRoute = DemoConvexAggregateRouteImport.update({
  id: '/demo/convex-aggregate',
  path: '/demo/convex-aggregate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexActionCacheRoute = DemoConvexActionCacheRouteImport.update({
  id: '/demo/convex-action-cache',
  path: '/demo/convex-action-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/_authenticated/authenticated',
    path: '/authenticated',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/convex-action-cache': typeof DemoConvexActionCacheRoute
  '/demo/convex-aggregate': typeof DemoConvexAggregateRoute
  '/demo/convex-api-credentials': typeof DemoConvexApiCredentialsRoute
  '/demo/convex-audit-log': typeof DemoConvexAuditLogRoute
  '/demo/convex-cascading-delete': typeof DemoConvexCascadingDeleteRoute
  '/demo/convex-crons': typeof DemoConvexCronsRoute
  '/demo/convex-debouncer': typeof DemoConvexDebouncerRoute
  '/demo/convex-file-management': typeof DemoConvexFileManagementRoute
  '/demo/convex-fluent': typeof DemoConvexFluentRoute
  '/demo/convex-geospatial': typeof DemoConvexGeospatialRoute
  '/demo/convex-migrations': typeof DemoConvexMigrationsRoute
  '/demo/convex-presence': typeof DemoConvexPresenceRoute
  '/demo/convex-rate-limiter': typeof DemoConvexRateLimiterRoute
  '/demo/convex-timeline': typeof DemoConvexTimelineRoute
  '/demo/convex-tracer': typeof DemoConvexTracerRoute
  '/demo/convex-triggers': typeof DemoConvexTriggersRoute
  '/demo/convex-workflow': typeof DemoConvexWorkflowRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/e2e/switch-org': typeof E2eSwitchOrgRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/convex-action-cache': typeof DemoConvexActionCacheRoute
  '/demo/convex-aggregate': typeof DemoConvexAggregateRoute
  '/demo/convex-api-credentials': typeof DemoConvexApiCredentialsRoute
  '/demo/convex-audit-log': typeof DemoConvexAuditLogRoute
  '/demo/convex-cascading-delete': typeof DemoConvexCascadingDeleteRoute
  '/demo/convex-crons': typeof DemoConvexCronsRoute
  '/demo/convex-debouncer': typeof DemoConvexDebouncerRoute
  '/demo/convex-file-management': typeof DemoConvexFileManagementRoute
  '/demo/convex-fluent': typeof DemoConvexFluentRoute
  '/demo/convex-geospatial': typeof DemoConvexGeospatialRoute
  '/demo/convex-migrations': typeof DemoConvexMigrationsRoute
  '/demo/convex-presence': typeof DemoConvexPresenceRoute
  '/demo/convex-rate-limiter': typeof DemoConvexRateLimiterRoute
  '/demo/convex-timeline': typeof DemoConvexTimelineRoute
  '/demo/convex-tracer': typeof DemoConvexTracerRoute
  '/demo/convex-triggers': typeof DemoConvexTriggersRoute
  '/demo/convex-workflow': typeof DemoConvexWorkflowRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/e2e/switch-org': typeof E2eSwitchOrgRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/convex-action-cache': typeof DemoConvexActionCacheRoute
  '/demo/convex-aggregate': typeof DemoConvexAggregateRoute
  '/demo/convex-api-credentials': typeof DemoConvexApiCredentialsRoute
  '/demo/convex-audit-log': typeof DemoConvexAuditLogRoute
  '/demo/convex-cascading-delete': typeof DemoConvexCascadingDeleteRoute
  '/demo/convex-crons': typeof DemoConvexCronsRoute
  '/demo/convex-debouncer': typeof DemoConvexDebouncerRoute
  '/demo/convex-file-management': typeof DemoConvexFileManagementRoute
  '/demo/convex-fluent': typeof DemoConvexFluentRoute
  '/demo/convex-geospatial': typeof DemoConvexGeospatialRoute
  '/demo/convex-migrations': typeof DemoConvexMigrationsRoute
  '/demo/convex-presence': typeof DemoConvexPresenceRoute
  '/demo/convex-rate-limiter': typeof DemoConvexRateLimiterRoute
  '/demo/convex-timeline': typeof DemoConvexTimelineRoute
  '/demo/convex-tracer': typeof DemoConvexTracerRoute
  '/demo/convex-triggers': typeof DemoConvexTriggersRoute
  '/demo/convex-workflow': typeof DemoConvexWorkflowRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/e2e/switch-org': typeof E2eSwitchOrgRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/callback'
    | '/sign-in'
    | '/sign-up'
    | '/authenticated'
    | '/demo/convex'
    | '/demo/convex-action-cache'
    | '/demo/convex-aggregate'
    | '/demo/convex-api-credentials'
    | '/demo/convex-audit-log'
    | '/demo/convex-cascading-delete'
    | '/demo/convex-crons'
    | '/demo/convex-debouncer'
    | '/demo/convex-file-management'
    | '/demo/convex-fluent'
    | '/demo/convex-geospatial'
    | '/demo/convex-migrations'
    | '/demo/convex-presence'
    | '/demo/convex-rate-limiter'
    | '/demo/convex-timeline'
    | '/demo/convex-tracer'
    | '/demo/convex-triggers'
    | '/demo/convex-workflow'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/e2e/switch-org'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/callback'
    | '/sign-in'
    | '/sign-up'
    | '/authenticated'
    | '/demo/convex'
    | '/demo/convex-action-cache'
    | '/demo/convex-aggregate'
    | '/demo/convex-api-credentials'
    | '/demo/convex-audit-log'
    | '/demo/convex-cascading-delete'
    | '/demo/convex-crons'
    | '/demo/convex-debouncer'
    | '/demo/convex-file-management'
    | '/demo/convex-fluent'
    | '/demo/convex-geospatial'
    | '/demo/convex-migrations'
    | '/demo/convex-presence'
    | '/demo/convex-rate-limiter'
    | '/demo/convex-timeline'
    | '/demo/convex-tracer'
    | '/demo/convex-triggers'
    | '/demo/convex-workflow'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/e2e/switch-org'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/callback'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/authenticated'
    | '/demo/convex'
    | '/demo/convex-action-cache'
    | '/demo/convex-aggregate'
    | '/demo/convex-api-credentials'
    | '/demo/convex-audit-log'
    | '/demo/convex-cascading-delete'
    | '/demo/convex-crons'
    | '/demo/convex-debouncer'
    | '/demo/convex-file-management'
    | '/demo/convex-fluent'
    | '/demo/convex-geospatial'
    | '/demo/convex-migrations'
    | '/demo/convex-presence'
    | '/demo/convex-rate-limiter'
    | '/demo/convex-timeline'
    | '/demo/convex-tracer'
    | '/demo/convex-triggers'
    | '/demo/convex-workflow'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/e2e/switch-org'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoConvexActionCacheRoute: typeof DemoConvexActionCacheRoute
  DemoConvexAggregateRoute: typeof DemoConvexAggregateRoute
  DemoConvexApiCredentialsRoute: typeof DemoConvexApiCredentialsRoute
  DemoConvexAuditLogRoute: typeof DemoConvexAuditLogRoute
  DemoConvexCascadingDeleteRoute: typeof DemoConvexCascadingDeleteRoute
  DemoConvexCronsRoute: typeof DemoConvexCronsRoute
  DemoConvexDebouncerRoute: typeof DemoConvexDebouncerRoute
  DemoConvexFileManagementRoute: typeof DemoConvexFileManagementRoute
  DemoConvexFluentRoute: typeof DemoConvexFluentRoute
  DemoConvexGeospatialRoute: typeof DemoConvexGeospatialRoute
  DemoConvexMigrationsRoute: typeof DemoConvexMigrationsRoute
  DemoConvexPresenceRoute: typeof DemoConvexPresenceRoute
  DemoConvexRateLimiterRoute: typeof DemoConvexRateLimiterRoute
  DemoConvexTimelineRoute: typeof DemoConvexTimelineRoute
  DemoConvexTracerRoute: typeof DemoConvexTracerRoute
  DemoConvexTriggersRoute: typeof DemoConvexTriggersRoute
  DemoConvexWorkflowRoute: typeof DemoConvexWorkflowRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  E2eSwitchOrgRoute: typeof E2eSwitchOrgRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/switch-org': {
      id: '/e2e/switch-org'
      path: '/e2e/switch-org'
      fullPath: '/e2e/switch-org'
      preLoaderRoute: typeof E2eSwitchOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-workflow': {
      id: '/demo/convex-workflow'
      path: '/demo/convex-workflow'
      fullPath: '/demo/convex-workflow'
      preLoaderRoute: typeof DemoConvexWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-triggers': {
      id: '/demo/convex-triggers'
      path: '/demo/convex-triggers'
      fullPath: '/demo/convex-triggers'
      preLoaderRoute: typeof DemoConvexTriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-tracer': {
      id: '/demo/convex-tracer'
      path: '/demo/convex-tracer'
      fullPath: '/demo/convex-tracer'
      preLoaderRoute: typeof DemoConvexTracerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-timeline': {
      id: '/demo/convex-timeline'
      path: '/demo/convex-timeline'
      fullPath: '/demo/convex-timeline'
      preLoaderRoute: typeof DemoConvexTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-rate-limiter': {
      id: '/demo/convex-rate-limiter'
      path: '/demo/convex-rate-limiter'
      fullPath: '/demo/convex-rate-limiter'
      preLoaderRoute: typeof DemoConvexRateLimiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-presence': {
      id: '/demo/convex-presence'
      path: '/demo/convex-presence'
      fullPath: '/demo/convex-presence'
      preLoaderRoute: typeof DemoConvexPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-migrations': {
      id: '/demo/convex-migrations'
      path: '/demo/convex-migrations'
      fullPath: '/demo/convex-migrations'
      preLoaderRoute: typeof DemoConvexMigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-geospatial': {
      id: '/demo/convex-geospatial'
      path: '/demo/convex-geospatial'
      fullPath: '/demo/convex-geospatial'
      preLoaderRoute: typeof DemoConvexGeospatialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-fluent': {
      id: '/demo/convex-fluent'
      path: '/demo/convex-fluent'
      fullPath: '/demo/convex-fluent'
      preLoaderRoute: typeof DemoConvexFluentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-file-management': {
      id: '/demo/convex-file-management'
      path: '/demo/convex-file-management'
      fullPath: '/demo/convex-file-management'
      preLoaderRoute: typeof DemoConvexFileManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-debouncer': {
      id: '/demo/convex-debouncer'
      path: '/demo/convex-debouncer'
      fullPath: '/demo/convex-debouncer'
      preLoaderRoute: typeof DemoConvexDebouncerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-crons': {
      id: '/demo/convex-crons'
      path: '/demo/convex-crons'
      fullPath: '/demo/convex-crons'
      preLoaderRoute: typeof DemoConvexCronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-cascading-delete': {
      id: '/demo/convex-cascading-delete'
      path: '/demo/convex-cascading-delete'
      fullPath: '/demo/convex-cascading-delete'
      preLoaderRoute: typeof DemoConvexCascadingDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-audit-log': {
      id: '/demo/convex-audit-log'
      path: '/demo/convex-audit-log'
      fullPath: '/demo/convex-audit-log'
      preLoaderRoute: typeof DemoConvexAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-api-credentials': {
      id: '/demo/convex-api-credentials'
      path: '/demo/convex-api-credentials'
      fullPath: '/demo/convex-api-credentials'
      preLoaderRoute: typeof DemoConvexApiCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-aggregate': {
      id: '/demo/convex-aggregate'
      path: '/demo/convex-aggregate'
      fullPath: '/demo/convex-aggregate'
      preLoaderRoute: typeof DemoConvexAggregateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-action-cache': {
      id: '/demo/convex-action-cache'
      path: '/demo/convex-action-cache'
      fullPath: '/demo/convex-action-cache'
      preLoaderRoute: typeof DemoConvexActionCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoConvexActionCacheRoute: DemoConvexActionCacheRoute,
  DemoConvexAggregateRoute: DemoConvexAggregateRoute,
  DemoConvexApiCredentialsRoute: DemoConvexApiCredentialsRoute,
  DemoConvexAuditLogRoute: DemoConvexAuditLogRoute,
  DemoConvexCascadingDeleteRoute: DemoConvexCascadingDeleteRoute,
  DemoConvexCronsRoute: DemoConvexCronsRoute,
  DemoConvexDebouncerRoute: DemoConvexDebouncerRoute,
  DemoConvexFileManagementRoute: DemoConvexFileManagementRoute,
  DemoConvexFluentRoute: DemoConvexFluentRoute,
  DemoConvexGeospatialRoute: DemoConvexGeospatialRoute,
  DemoConvexMigrationsRoute: DemoConvexMigrationsRoute,
  DemoConvexPresenceRoute: DemoConvexPresenceRoute,
  DemoConvexRateLimiterRoute: DemoConvexRateLimiterRoute,
  DemoConvexTimelineRoute: DemoConvexTimelineRoute,
  DemoConvexTracerRoute: DemoConvexTracerRoute,
  DemoConvexTriggersRoute: DemoConvexTriggersRoute,
  DemoConvexWorkflowRoute: DemoConvexWorkflowRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  E2eSwitchOrgRoute: E2eSwitchOrgRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
