/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OnboardRouteRouteImport } from './routes/onboard/route'
import { Route as LenderRouteRouteImport } from './routes/lender/route'
import { Route as LawyerRouteRouteImport } from './routes/lawyer/route'
import { Route as BrokerRouteRouteImport } from './routes/broker/route'
import { Route as BorrowerRouteRouteImport } from './routes/borrower/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as E2eSwitchOrgRouteImport } from './routes/e2e/switch-org'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoSimulationRouteImport } from './routes/demo/simulation'
import { Route as DemoProdLedgerRouteImport } from './routes/demo/prod-ledger'
import { Route as DemoListingsRouteImport } from './routes/demo.listings'
import { Route as DemoConvexWorkflowRouteImport } from './routes/demo/convex-workflow'
import { Route as DemoConvexTriggersRouteImport } from './routes/demo/convex-triggers'
import { Route as DemoConvexTracerRouteImport } from './routes/demo/convex-tracer'
import { Route as DemoConvexTimelineRouteImport } from './routes/demo/convex-timeline'
import { Route as DemoConvexRateLimiterRouteImport } from './routes/demo/convex-rate-limiter'
import { Route as DemoConvexPresenceRouteImport } from './routes/demo/convex-presence'
import { Route as DemoConvexMigrationsRouteImport } from './routes/demo/convex-migrations'
import { Route as DemoConvexLedgerRouteImport } from './routes/demo/convex-ledger'
import { Route as DemoConvexGeospatialRouteImport } from './routes/demo/convex-geospatial'
import { Route as DemoConvexFluentRouteImport } from './routes/demo/convex-fluent'
import { Route as DemoConvexFileManagementRouteImport } from './routes/demo/convex-file-management'
import { Route as DemoConvexDebouncerRouteImport } from './routes/demo/convex-debouncer'
import { Route as DemoConvexCronsRouteImport } from './routes/demo/convex-crons'
import { Route as DemoConvexCascadingDeleteRouteImport } from './routes/demo/convex-cascading-delete'
import { Route as DemoConvexAuditLogRouteImport } from './routes/demo/convex-audit-log'
import { Route as DemoConvexApiCredentialsRouteImport } from './routes/demo/convex-api-credentials'
import { Route as DemoConvexAggregateRouteImport } from './routes/demo/convex-aggregate'
import { Route as DemoConvexActionCacheRouteImport } from './routes/demo/convex-action-cache'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as AdminEntitytypeRouteImport } from './routes/admin/$entitytype'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as DemoRbacAuthRouteRouteImport } from './routes/demo/rbac-auth/route'
import { Route as DemoRbacRouteRouteImport } from './routes/demo/rbac/route'
import { Route as DemoGovernedTransitionsRouteRouteImport } from './routes/demo/governed-transitions/route'
import { Route as DemoDocumentEngineRouteRouteImport } from './routes/demo/document-engine/route'
import { Route as DemoCrmRouteRouteImport } from './routes/demo/crm/route'
import { Route as DemoAuditTraceabilityRouteRouteImport } from './routes/demo/audit-traceability/route'
import { Route as DemoAmpsRouteRouteImport } from './routes/demo/amps/route'
import { Route as AdminUnderwritingRouteRouteImport } from './routes/admin/underwriting/route'
import { Route as AdminPropertiesRouteRouteImport } from './routes/admin/properties/route'
import { Route as AdminObligationsRouteRouteImport } from './routes/admin/obligations/route'
import { Route as AdminMortgagesRouteRouteImport } from './routes/admin/mortgages/route'
import { Route as AdminListingsRouteRouteImport } from './routes/admin/listings/route'
import { Route as AdminDealsRouteRouteImport } from './routes/admin/deals/route'
import { Route as AdminBorrowersRouteRouteImport } from './routes/admin/borrowers/route'
import { Route as DemoRbacIndexRouteImport } from './routes/demo/rbac/index'
import { Route as DemoRbacAuthIndexRouteImport } from './routes/demo/rbac-auth/index'
import { Route as DemoListingsIndexRouteImport } from './routes/demo/listings/index'
import { Route as DemoGovernedTransitionsIndexRouteImport } from './routes/demo/governed-transitions/index'
import { Route as DemoDocumentEngineIndexRouteImport } from './routes/demo/document-engine/index'
import { Route as DemoCrmIndexRouteImport } from './routes/demo/crm/index'
import { Route as DemoAuditTraceabilityIndexRouteImport } from './routes/demo/audit-traceability/index'
import { Route as DemoAmpsIndexRouteImport } from './routes/demo/amps/index'
import { Route as DemoRbacAuthRolesRouteImport } from './routes/demo/rbac-auth/roles'
import { Route as DemoRbacAuthOnboardingRouteImport } from './routes/demo/rbac-auth/onboarding'
import { Route as DemoRbacAuthAuditRouteImport } from './routes/demo/rbac-auth/audit'
import { Route as DemoRbacAuthAccessControlRouteImport } from './routes/demo/rbac-auth/access-control'
import { Route as DemoListingsListingidRouteImport } from './routes/demo/listings/$listingid'
import { Route as DemoGovernedTransitionsMachineRouteImport } from './routes/demo/governed-transitions/machine'
import { Route as DemoGovernedTransitionsJournalRouteImport } from './routes/demo/governed-transitions/journal'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoDocumentEngineVariablesRouteImport } from './routes/demo/document-engine/variables'
import { Route as DemoDocumentEngineTemplatesRouteImport } from './routes/demo/document-engine/templates'
import { Route as DemoDocumentEngineLibraryRouteImport } from './routes/demo/document-engine/library'
import { Route as DemoDocumentEngineGroupsRouteImport } from './routes/demo/document-engine/groups'
import { Route as DemoDocumentEngineGenerateRouteImport } from './routes/demo/document-engine/generate'
import { Route as DemoCrmSystemRouteImport } from './routes/demo/crm/system'
import { Route as DemoCrmLinksRouteImport } from './routes/demo/crm/links'
import { Route as DemoAuditTraceabilityReportRouteImport } from './routes/demo/audit-traceability/report'
import { Route as DemoAuditTraceabilityPipelineRouteImport } from './routes/demo/audit-traceability/pipeline'
import { Route as DemoAuditTraceabilityHashChainRouteImport } from './routes/demo/audit-traceability/hash-chain'
import { Route as DemoAuditTraceabilityAuditTrailRouteImport } from './routes/demo/audit-traceability/audit-trail'
import { Route as DemoAuditTraceabilityAccessLogRouteImport } from './routes/demo/audit-traceability/access-log'
import { Route as DemoAmpsRulesRouteImport } from './routes/demo/amps/rules'
import { Route as DemoAmpsE2ePaymentsRouteImport } from './routes/demo/amps/e2e-payments'
import { Route as DemoAmpsCollectionPlanRouteImport } from './routes/demo/amps/collection-plan'
import { Route as DemoAmpsCollectionAttemptsRouteImport } from './routes/demo/amps/collection-attempts'
import { Route as AdminPropertiesRecordidRouteImport } from './routes/admin/properties/$recordid'
import { Route as AdminObligationsRecordidRouteImport } from './routes/admin/obligations/$recordid'
import { Route as AdminMortgagesRecordidRouteImport } from './routes/admin/mortgages/$recordid'
import { Route as AdminListingsRecordidRouteImport } from './routes/admin/listings/$recordid'
import { Route as AdminDealsRecordidRouteImport } from './routes/admin/deals/$recordid'
import { Route as AdminBorrowersRecordidRouteImport } from './routes/admin/borrowers/$recordid'
import { Route as AdminEntitytypeRecordidRouteImport } from './routes/admin/$entitytype.$recordid'
import { Route as DemoRbacLenderRouteRouteImport } from './routes/demo/rbac/lender/route'
import { Route as DemoRbacLawyerRouteRouteImport } from './routes/demo/rbac/lawyer/route'
import { Route as DemoRbacBrokerRouteRouteImport } from './routes/demo/rbac/broker/route'
import { Route as DemoRbacBorrowerRouteRouteImport } from './routes/demo/rbac/borrower/route'
import { Route as DemoRbacAdminRouteRouteImport } from './routes/demo/rbac/admin/route'
import { Route as DemoDocumentEngineDesignerTemplateIdRouteImport } from './routes/demo/document-engine/designer.$templateId'
import { Route as DemoCrmObjectDefIdRecordIdRouteImport } from './routes/demo/crm/$objectDefId.$recordId'
import { Route as DemoRbacAdminUnderwritingRouteRouteImport } from './routes/demo/rbac/admin/underwriting/route'
import { Route as DemoAmpsMortgagesMortgageIdPaymentsRouteImport } from './routes/demo/amps/mortgages.$mortgageId.payments'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRouteRoute = OnboardRouteRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderRouteRoute = LenderRouteRouteImport.update({
  id: '/lender',
  path: '/lender',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerRouteRoute = LawyerRouteRouteImport.update({
  id: '/lawyer',
  path: '/lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRouteRoute = BrokerRouteRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowerRouteRoute = BorrowerRouteRouteImport.update({
  id: '/borrower',
  path: '/borrower',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eSwitchOrgRoute = E2eSwitchOrgRouteImport.update({
  id: '/e2e/switch-org',
  path: '/e2e/switch-org',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSimulationRoute = DemoSimulationRouteImport.update({
  id: '/demo/simulation',
  path: '/demo/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProdLedgerRoute = DemoProdLedgerRouteImport.update({
  id: '/demo/prod-ledger',
  path: '/demo/prod-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoListingsRoute = DemoListingsRouteImport.update({
  id: '/demo/listings',
  path: '/demo/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexWorkflowRoute = DemoConvexWorkflowRouteImport.update({
  id: '/demo/convex-workflow',
  path: '/demo/convex-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexTriggersRoute = DemoConvexTriggersRouteImport.update({
  id: '/demo/convex-triggers',
  path: '/demo/convex-triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexTracerRoute = DemoConvexTracerRouteImport.update({
  id: '/demo/convex-tracer',
  path: '/demo/convex-tracer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexTimelineRoute = DemoConvexTimelineRouteImport.update({
  id: '/demo/convex-timeline',
  path: '/demo/convex-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRateLimiterRoute = DemoConvexRateLimiterRouteImport.update({
  id: '/demo/convex-rate-limiter',
  path: '/demo/convex-rate-limiter',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexPresenceRoute = DemoConvexPresenceRouteImport.update({
  id: '/demo/convex-presence',
  path: '/demo/convex-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexMigrationsRoute = DemoConvexMigrationsRouteImport.update({
  id: '/demo/convex-migrations',
  path: '/demo/convex-migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexLedgerRoute = DemoConvexLedgerRouteImport.update({
  id: '/demo/convex-ledger',
  path: '/demo/convex-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexGeospatialRoute = DemoConvexGeospatialRouteImport.update({
  id: '/demo/convex-geospatial',
  path: '/demo/convex-geospatial',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexFluentRoute = DemoConvexFluentRouteImport.update({
  id: '/demo/convex-fluent',
  path: '/demo/convex-fluent',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexFileManagementRoute =
  DemoConvexFileManagementRouteImport.update({
    id: '/demo/convex-file-management',
    path: '/demo/convex-file-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoConvexDebouncerRoute = DemoConvexDebouncerRouteImport.update({
  id: '/demo/convex-debouncer',
  path: '/demo/convex-debouncer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexCronsRoute = DemoConvexCronsRouteImport.update({
  id: '/demo/convex-crons',
  path: '/demo/convex-crons',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexCascadingDeleteRoute =
  DemoConvexCascadingDeleteRouteImport.update({
    id: '/demo/convex-cascading-delete',
    path: '/demo/convex-cascading-delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoConvexAuditLogRoute = DemoConvexAuditLogRouteImport.update({
  id: '/demo/convex-audit-log',
  path: '/demo/convex-audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexApiCredentialsRoute =
  DemoConvexApiCredentialsRouteImport.update({
    id: '/demo/convex-api-credentials',
    path: '/demo/convex-api-credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoConvexAggregateRoute = DemoConvexAggregateRouteImport.update({
  id: '/demo/convex-aggregate',
  path: '/demo/convex-aggregate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexActionCacheRoute = DemoConvexActionCacheRouteImport.update({
  id: '/demo/convex-action-cache',
  path: '/demo/convex-action-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntitytypeRoute = AdminEntitytypeRouteImport.update({
  id: '/$entitytype',
  path: '/$entitytype',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/_authenticated/authenticated',
    path: '/authenticated',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoRbacAuthRouteRoute = DemoRbacAuthRouteRouteImport.update({
  id: '/demo/rbac-auth',
  path: '/demo/rbac-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRbacRouteRoute = DemoRbacRouteRouteImport.update({
  id: '/demo/rbac',
  path: '/demo/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGovernedTransitionsRouteRoute =
  DemoGovernedTransitionsRouteRouteImport.update({
    id: '/demo/governed-transitions',
    path: '/demo/governed-transitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoDocumentEngineRouteRoute = DemoDocumentEngineRouteRouteImport.update({
  id: '/demo/document-engine',
  path: '/demo/document-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCrmRouteRoute = DemoCrmRouteRouteImport.update({
  id: '/demo/crm',
  path: '/demo/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAuditTraceabilityRouteRoute =
  DemoAuditTraceabilityRouteRouteImport.update({
    id: '/demo/audit-traceability',
    path: '/demo/audit-traceability',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoAmpsRouteRoute = DemoAmpsRouteRouteImport.update({
  id: '/demo/amps',
  path: '/demo/amps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnderwritingRouteRoute = AdminUnderwritingRouteRouteImport.update({
  id: '/underwriting',
  path: '/underwriting',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPropertiesRouteRoute = AdminPropertiesRouteRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminObligationsRouteRoute = AdminObligationsRouteRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMortgagesRouteRoute = AdminMortgagesRouteRouteImport.update({
  id: '/mortgages',
  path: '/mortgages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsRouteRoute = AdminListingsRouteRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDealsRouteRoute = AdminDealsRouteRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBorrowersRouteRoute = AdminBorrowersRouteRouteImport.update({
  id: '/borrowers',
  path: '/borrowers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoRbacIndexRoute = DemoRbacIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRbacRouteRoute,
} as any)
const DemoRbacAuthIndexRoute = DemoRbacAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRbacAuthRouteRoute,
} as any)
const DemoListingsIndexRoute = DemoListingsIndexRouteImport.update({
  id: '/demo/listings/',
  path: '/demo/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGovernedTransitionsIndexRoute =
  DemoGovernedTransitionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DemoGovernedTransitionsRouteRoute,
  } as any)
const DemoDocumentEngineIndexRoute = DemoDocumentEngineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoDocumentEngineRouteRoute,
} as any)
const DemoCrmIndexRoute = DemoCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoCrmRouteRoute,
} as any)
const DemoAuditTraceabilityIndexRoute =
  DemoAuditTraceabilityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DemoAuditTraceabilityRouteRoute,
  } as any)
const DemoAmpsIndexRoute = DemoAmpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoAmpsRouteRoute,
} as any)
const DemoRbacAuthRolesRoute = DemoRbacAuthRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DemoRbacAuthRouteRoute,
} as any)
const DemoRbacAuthOnboardingRoute = DemoRbacAuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DemoRbacAuthRouteRoute,
} as any)
const DemoRbacAuthAuditRoute = DemoRbacAuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DemoRbacAuthRouteRoute,
} as any)
const DemoRbacAuthAccessControlRoute =
  DemoRbacAuthAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => DemoRbacAuthRouteRoute,
  } as any)
const DemoListingsListingidRoute = DemoListingsListingidRouteImport.update({
  id: '/demo/listings/$listingid',
  path: '/demo/listings/$listingid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGovernedTransitionsMachineRoute =
  DemoGovernedTransitionsMachineRouteImport.update({
    id: '/machine',
    path: '/machine',
    getParentRoute: () => DemoGovernedTransitionsRouteRoute,
  } as any)
const DemoGovernedTransitionsJournalRoute =
  DemoGovernedTransitionsJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => DemoGovernedTransitionsRouteRoute,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDocumentEngineVariablesRoute =
  DemoDocumentEngineVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => DemoDocumentEngineRouteRoute,
  } as any)
const DemoDocumentEngineTemplatesRoute =
  DemoDocumentEngineTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DemoDocumentEngineRouteRoute,
  } as any)
const DemoDocumentEngineLibraryRoute =
  DemoDocumentEngineLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => DemoDocumentEngineRouteRoute,
  } as any)
const DemoDocumentEngineGroupsRoute =
  DemoDocumentEngineGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => DemoDocumentEngineRouteRoute,
  } as any)
const DemoDocumentEngineGenerateRoute =
  DemoDocumentEngineGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => DemoDocumentEngineRouteRoute,
  } as any)
const DemoCrmSystemRoute = DemoCrmSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DemoCrmRouteRoute,
} as any)
const DemoCrmLinksRoute = DemoCrmLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DemoCrmRouteRoute,
} as any)
const DemoAuditTraceabilityReportRoute =
  DemoAuditTraceabilityReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => DemoAuditTraceabilityRouteRoute,
  } as any)
const DemoAuditTraceabilityPipelineRoute =
  DemoAuditTraceabilityPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => DemoAuditTraceabilityRouteRoute,
  } as any)
const DemoAuditTraceabilityHashChainRoute =
  DemoAuditTraceabilityHashChainRouteImport.update({
    id: '/hash-chain',
    path: '/hash-chain',
    getParentRoute: () => DemoAuditTraceabilityRouteRoute,
  } as any)
const DemoAuditTraceabilityAuditTrailRoute =
  DemoAuditTraceabilityAuditTrailRouteImport.update({
    id: '/audit-trail',
    path: '/audit-trail',
    getParentRoute: () => DemoAuditTraceabilityRouteRoute,
  } as any)
const DemoAuditTraceabilityAccessLogRoute =
  DemoAuditTraceabilityAccessLogRouteImport.update({
    id: '/access-log',
    path: '/access-log',
    getParentRoute: () => DemoAuditTraceabilityRouteRoute,
  } as any)
const DemoAmpsRulesRoute = DemoAmpsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DemoAmpsRouteRoute,
} as any)
const DemoAmpsE2ePaymentsRoute = DemoAmpsE2ePaymentsRouteImport.update({
  id: '/e2e-payments',
  path: '/e2e-payments',
  getParentRoute: () => DemoAmpsRouteRoute,
} as any)
const DemoAmpsCollectionPlanRoute = DemoAmpsCollectionPlanRouteImport.update({
  id: '/collection-plan',
  path: '/collection-plan',
  getParentRoute: () => DemoAmpsRouteRoute,
} as any)
const DemoAmpsCollectionAttemptsRoute =
  DemoAmpsCollectionAttemptsRouteImport.update({
    id: '/collection-attempts',
    path: '/collection-attempts',
    getParentRoute: () => DemoAmpsRouteRoute,
  } as any)
const AdminPropertiesRecordidRoute = AdminPropertiesRecordidRouteImport.update({
  id: '/$recordid',
  path: '/$recordid',
  getParentRoute: () => AdminPropertiesRouteRoute,
} as any)
const AdminObligationsRecordidRoute =
  AdminObligationsRecordidRouteImport.update({
    id: '/$recordid',
    path: '/$recordid',
    getParentRoute: () => AdminObligationsRouteRoute,
  } as any)
const AdminMortgagesRecordidRoute = AdminMortgagesRecordidRouteImport.update({
  id: '/$recordid',
  path: '/$recordid',
  getParentRoute: () => AdminMortgagesRouteRoute,
} as any)
const AdminListingsRecordidRoute = AdminListingsRecordidRouteImport.update({
  id: '/$recordid',
  path: '/$recordid',
  getParentRoute: () => AdminListingsRouteRoute,
} as any)
const AdminDealsRecordidRoute = AdminDealsRecordidRouteImport.update({
  id: '/$recordid',
  path: '/$recordid',
  getParentRoute: () => AdminDealsRouteRoute,
} as any)
const AdminBorrowersRecordidRoute = AdminBorrowersRecordidRouteImport.update({
  id: '/$recordid',
  path: '/$recordid',
  getParentRoute: () => AdminBorrowersRouteRoute,
} as any)
const AdminEntitytypeRecordidRoute = AdminEntitytypeRecordidRouteImport.update({
  id: '/$recordid',
  path: '/$recordid',
  getParentRoute: () => AdminEntitytypeRoute,
} as any)
const DemoRbacLenderRouteRoute = DemoRbacLenderRouteRouteImport.update({
  id: '/lender',
  path: '/lender',
  getParentRoute: () => DemoRbacRouteRoute,
} as any)
const DemoRbacLawyerRouteRoute = DemoRbacLawyerRouteRouteImport.update({
  id: '/lawyer',
  path: '/lawyer',
  getParentRoute: () => DemoRbacRouteRoute,
} as any)
const DemoRbacBrokerRouteRoute = DemoRbacBrokerRouteRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => DemoRbacRouteRoute,
} as any)
const DemoRbacBorrowerRouteRoute = DemoRbacBorrowerRouteRouteImport.update({
  id: '/borrower',
  path: '/borrower',
  getParentRoute: () => DemoRbacRouteRoute,
} as any)
const DemoRbacAdminRouteRoute = DemoRbacAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DemoRbacRouteRoute,
} as any)
const DemoDocumentEngineDesignerTemplateIdRoute =
  DemoDocumentEngineDesignerTemplateIdRouteImport.update({
    id: '/designer/$templateId',
    path: '/designer/$templateId',
    getParentRoute: () => DemoDocumentEngineRouteRoute,
  } as any)
const DemoCrmObjectDefIdRecordIdRoute =
  DemoCrmObjectDefIdRecordIdRouteImport.update({
    id: '/$objectDefId/$recordId',
    path: '/$objectDefId/$recordId',
    getParentRoute: () => DemoCrmRouteRoute,
  } as any)
const DemoRbacAdminUnderwritingRouteRoute =
  DemoRbacAdminUnderwritingRouteRouteImport.update({
    id: '/underwriting',
    path: '/underwriting',
    getParentRoute: () => DemoRbacAdminRouteRoute,
  } as any)
const DemoAmpsMortgagesMortgageIdPaymentsRoute =
  DemoAmpsMortgagesMortgageIdPaymentsRouteImport.update({
    id: '/mortgages/$mortgageId/payments',
    path: '/mortgages/$mortgageId/payments',
    getParentRoute: () => DemoAmpsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/borrower': typeof BorrowerRouteRoute
  '/broker': typeof BrokerRouteRoute
  '/lawyer': typeof LawyerRouteRoute
  '/lender': typeof LenderRouteRoute
  '/onboard': typeof OnboardRouteRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/borrowers': typeof AdminBorrowersRouteRouteWithChildren
  '/admin/deals': typeof AdminDealsRouteRouteWithChildren
  '/admin/listings': typeof AdminListingsRouteRouteWithChildren
  '/admin/mortgages': typeof AdminMortgagesRouteRouteWithChildren
  '/admin/obligations': typeof AdminObligationsRouteRouteWithChildren
  '/admin/properties': typeof AdminPropertiesRouteRouteWithChildren
  '/admin/underwriting': typeof AdminUnderwritingRouteRoute
  '/demo/amps': typeof DemoAmpsRouteRouteWithChildren
  '/demo/audit-traceability': typeof DemoAuditTraceabilityRouteRouteWithChildren
  '/demo/crm': typeof DemoCrmRouteRouteWithChildren
  '/demo/document-engine': typeof DemoDocumentEngineRouteRouteWithChildren
  '/demo/governed-transitions': typeof DemoGovernedTransitionsRouteRouteWithChildren
  '/demo/rbac': typeof DemoRbacRouteRouteWithChildren
  '/demo/rbac-auth': typeof DemoRbacAuthRouteRouteWithChildren
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/admin/$entitytype': typeof AdminEntitytypeRouteWithChildren
  '/demo/convex': typeof DemoConvexRoute
  '/demo/convex-action-cache': typeof DemoConvexActionCacheRoute
  '/demo/convex-aggregate': typeof DemoConvexAggregateRoute
  '/demo/convex-api-credentials': typeof DemoConvexApiCredentialsRoute
  '/demo/convex-audit-log': typeof DemoConvexAuditLogRoute
  '/demo/convex-cascading-delete': typeof DemoConvexCascadingDeleteRoute
  '/demo/convex-crons': typeof DemoConvexCronsRoute
  '/demo/convex-debouncer': typeof DemoConvexDebouncerRoute
  '/demo/convex-file-management': typeof DemoConvexFileManagementRoute
  '/demo/convex-fluent': typeof DemoConvexFluentRoute
  '/demo/convex-geospatial': typeof DemoConvexGeospatialRoute
  '/demo/convex-ledger': typeof DemoConvexLedgerRoute
  '/demo/convex-migrations': typeof DemoConvexMigrationsRoute
  '/demo/convex-presence': typeof DemoConvexPresenceRoute
  '/demo/convex-rate-limiter': typeof DemoConvexRateLimiterRoute
  '/demo/convex-timeline': typeof DemoConvexTimelineRoute
  '/demo/convex-tracer': typeof DemoConvexTracerRoute
  '/demo/convex-triggers': typeof DemoConvexTriggersRoute
  '/demo/convex-workflow': typeof DemoConvexWorkflowRoute
  '/demo/listings': typeof DemoListingsRoute
  '/demo/prod-ledger': typeof DemoProdLedgerRoute
  '/demo/simulation': typeof DemoSimulationRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/e2e/switch-org': typeof E2eSwitchOrgRoute
  '/demo/rbac/admin': typeof DemoRbacAdminRouteRouteWithChildren
  '/demo/rbac/borrower': typeof DemoRbacBorrowerRouteRoute
  '/demo/rbac/broker': typeof DemoRbacBrokerRouteRoute
  '/demo/rbac/lawyer': typeof DemoRbacLawyerRouteRoute
  '/demo/rbac/lender': typeof DemoRbacLenderRouteRoute
  '/admin/$entitytype/$recordid': typeof AdminEntitytypeRecordidRoute
  '/admin/borrowers/$recordid': typeof AdminBorrowersRecordidRoute
  '/admin/deals/$recordid': typeof AdminDealsRecordidRoute
  '/admin/listings/$recordid': typeof AdminListingsRecordidRoute
  '/admin/mortgages/$recordid': typeof AdminMortgagesRecordidRoute
  '/admin/obligations/$recordid': typeof AdminObligationsRecordidRoute
  '/admin/properties/$recordid': typeof AdminPropertiesRecordidRoute
  '/demo/amps/collection-attempts': typeof DemoAmpsCollectionAttemptsRoute
  '/demo/amps/collection-plan': typeof DemoAmpsCollectionPlanRoute
  '/demo/amps/e2e-payments': typeof DemoAmpsE2ePaymentsRoute
  '/demo/amps/rules': typeof DemoAmpsRulesRoute
  '/demo/audit-traceability/access-log': typeof DemoAuditTraceabilityAccessLogRoute
  '/demo/audit-traceability/audit-trail': typeof DemoAuditTraceabilityAuditTrailRoute
  '/demo/audit-traceability/hash-chain': typeof DemoAuditTraceabilityHashChainRoute
  '/demo/audit-traceability/pipeline': typeof DemoAuditTraceabilityPipelineRoute
  '/demo/audit-traceability/report': typeof DemoAuditTraceabilityReportRoute
  '/demo/crm/links': typeof DemoCrmLinksRoute
  '/demo/crm/system': typeof DemoCrmSystemRoute
  '/demo/document-engine/generate': typeof DemoDocumentEngineGenerateRoute
  '/demo/document-engine/groups': typeof DemoDocumentEngineGroupsRoute
  '/demo/document-engine/library': typeof DemoDocumentEngineLibraryRoute
  '/demo/document-engine/templates': typeof DemoDocumentEngineTemplatesRoute
  '/demo/document-engine/variables': typeof DemoDocumentEngineVariablesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/governed-transitions/journal': typeof DemoGovernedTransitionsJournalRoute
  '/demo/governed-transitions/machine': typeof DemoGovernedTransitionsMachineRoute
  '/demo/listings/$listingid': typeof DemoListingsListingidRoute
  '/demo/rbac-auth/access-control': typeof DemoRbacAuthAccessControlRoute
  '/demo/rbac-auth/audit': typeof DemoRbacAuthAuditRoute
  '/demo/rbac-auth/onboarding': typeof DemoRbacAuthOnboardingRoute
  '/demo/rbac-auth/roles': typeof DemoRbacAuthRolesRoute
  '/demo/amps/': typeof DemoAmpsIndexRoute
  '/demo/audit-traceability/': typeof DemoAuditTraceabilityIndexRoute
  '/demo/crm/': typeof DemoCrmIndexRoute
  '/demo/document-engine/': typeof DemoDocumentEngineIndexRoute
  '/demo/governed-transitions/': typeof DemoGovernedTransitionsIndexRoute
  '/demo/listings/': typeof DemoListingsIndexRoute
  '/demo/rbac-auth/': typeof DemoRbacAuthIndexRoute
  '/demo/rbac/': typeof DemoRbacIndexRoute
  '/demo/rbac/admin/underwriting': typeof DemoRbacAdminUnderwritingRouteRoute
  '/demo/crm/$objectDefId/$recordId': typeof DemoCrmObjectDefIdRecordIdRoute
  '/demo/document-engine/designer/$templateId': typeof DemoDocumentEngineDesignerTemplateIdRoute
  '/demo/amps/mortgages/$mortgageId/payments': typeof DemoAmpsMortgagesMortgageIdPaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/borrower': typeof BorrowerRouteRoute
  '/broker': typeof BrokerRouteRoute
  '/lawyer': typeof LawyerRouteRoute
  '/lender': typeof LenderRouteRoute
  '/onboard': typeof OnboardRouteRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/borrowers': typeof AdminBorrowersRouteRouteWithChildren
  '/admin/deals': typeof AdminDealsRouteRouteWithChildren
  '/admin/listings': typeof AdminListingsRouteRouteWithChildren
  '/admin/mortgages': typeof AdminMortgagesRouteRouteWithChildren
  '/admin/obligations': typeof AdminObligationsRouteRouteWithChildren
  '/admin/properties': typeof AdminPropertiesRouteRouteWithChildren
  '/admin/underwriting': typeof AdminUnderwritingRouteRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/admin/$entitytype': typeof AdminEntitytypeRouteWithChildren
  '/demo/convex': typeof DemoConvexRoute
  '/demo/convex-action-cache': typeof DemoConvexActionCacheRoute
  '/demo/convex-aggregate': typeof DemoConvexAggregateRoute
  '/demo/convex-api-credentials': typeof DemoConvexApiCredentialsRoute
  '/demo/convex-audit-log': typeof DemoConvexAuditLogRoute
  '/demo/convex-cascading-delete': typeof DemoConvexCascadingDeleteRoute
  '/demo/convex-crons': typeof DemoConvexCronsRoute
  '/demo/convex-debouncer': typeof DemoConvexDebouncerRoute
  '/demo/convex-file-management': typeof DemoConvexFileManagementRoute
  '/demo/convex-fluent': typeof DemoConvexFluentRoute
  '/demo/convex-geospatial': typeof DemoConvexGeospatialRoute
  '/demo/convex-ledger': typeof DemoConvexLedgerRoute
  '/demo/convex-migrations': typeof DemoConvexMigrationsRoute
  '/demo/convex-presence': typeof DemoConvexPresenceRoute
  '/demo/convex-rate-limiter': typeof DemoConvexRateLimiterRoute
  '/demo/convex-timeline': typeof DemoConvexTimelineRoute
  '/demo/convex-tracer': typeof DemoConvexTracerRoute
  '/demo/convex-triggers': typeof DemoConvexTriggersRoute
  '/demo/convex-workflow': typeof DemoConvexWorkflowRoute
  '/demo/listings': typeof DemoListingsRoute
  '/demo/prod-ledger': typeof DemoProdLedgerRoute
  '/demo/simulation': typeof DemoSimulationRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/e2e/switch-org': typeof E2eSwitchOrgRoute
  '/demo/rbac/admin': typeof DemoRbacAdminRouteRouteWithChildren
  '/demo/rbac/borrower': typeof DemoRbacBorrowerRouteRoute
  '/demo/rbac/broker': typeof DemoRbacBrokerRouteRoute
  '/demo/rbac/lawyer': typeof DemoRbacLawyerRouteRoute
  '/demo/rbac/lender': typeof DemoRbacLenderRouteRoute
  '/admin/$entitytype/$recordid': typeof AdminEntitytypeRecordidRoute
  '/admin/borrowers/$recordid': typeof AdminBorrowersRecordidRoute
  '/admin/deals/$recordid': typeof AdminDealsRecordidRoute
  '/admin/listings/$recordid': typeof AdminListingsRecordidRoute
  '/admin/mortgages/$recordid': typeof AdminMortgagesRecordidRoute
  '/admin/obligations/$recordid': typeof AdminObligationsRecordidRoute
  '/admin/properties/$recordid': typeof AdminPropertiesRecordidRoute
  '/demo/amps/collection-attempts': typeof DemoAmpsCollectionAttemptsRoute
  '/demo/amps/collection-plan': typeof DemoAmpsCollectionPlanRoute
  '/demo/amps/e2e-payments': typeof DemoAmpsE2ePaymentsRoute
  '/demo/amps/rules': typeof DemoAmpsRulesRoute
  '/demo/audit-traceability/access-log': typeof DemoAuditTraceabilityAccessLogRoute
  '/demo/audit-traceability/audit-trail': typeof DemoAuditTraceabilityAuditTrailRoute
  '/demo/audit-traceability/hash-chain': typeof DemoAuditTraceabilityHashChainRoute
  '/demo/audit-traceability/pipeline': typeof DemoAuditTraceabilityPipelineRoute
  '/demo/audit-traceability/report': typeof DemoAuditTraceabilityReportRoute
  '/demo/crm/links': typeof DemoCrmLinksRoute
  '/demo/crm/system': typeof DemoCrmSystemRoute
  '/demo/document-engine/generate': typeof DemoDocumentEngineGenerateRoute
  '/demo/document-engine/groups': typeof DemoDocumentEngineGroupsRoute
  '/demo/document-engine/library': typeof DemoDocumentEngineLibraryRoute
  '/demo/document-engine/templates': typeof DemoDocumentEngineTemplatesRoute
  '/demo/document-engine/variables': typeof DemoDocumentEngineVariablesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/governed-transitions/journal': typeof DemoGovernedTransitionsJournalRoute
  '/demo/governed-transitions/machine': typeof DemoGovernedTransitionsMachineRoute
  '/demo/listings/$listingid': typeof DemoListingsListingidRoute
  '/demo/rbac-auth/access-control': typeof DemoRbacAuthAccessControlRoute
  '/demo/rbac-auth/audit': typeof DemoRbacAuthAuditRoute
  '/demo/rbac-auth/onboarding': typeof DemoRbacAuthOnboardingRoute
  '/demo/rbac-auth/roles': typeof DemoRbacAuthRolesRoute
  '/demo/amps': typeof DemoAmpsIndexRoute
  '/demo/audit-traceability': typeof DemoAuditTraceabilityIndexRoute
  '/demo/crm': typeof DemoCrmIndexRoute
  '/demo/document-engine': typeof DemoDocumentEngineIndexRoute
  '/demo/governed-transitions': typeof DemoGovernedTransitionsIndexRoute
  '/demo/listings': typeof DemoListingsIndexRoute
  '/demo/rbac-auth': typeof DemoRbacAuthIndexRoute
  '/demo/rbac': typeof DemoRbacIndexRoute
  '/demo/rbac/admin/underwriting': typeof DemoRbacAdminUnderwritingRouteRoute
  '/demo/crm/$objectDefId/$recordId': typeof DemoCrmObjectDefIdRecordIdRoute
  '/demo/document-engine/designer/$templateId': typeof DemoDocumentEngineDesignerTemplateIdRoute
  '/demo/amps/mortgages/$mortgageId/payments': typeof DemoAmpsMortgagesMortgageIdPaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/borrower': typeof BorrowerRouteRoute
  '/broker': typeof BrokerRouteRoute
  '/lawyer': typeof LawyerRouteRoute
  '/lender': typeof LenderRouteRoute
  '/onboard': typeof OnboardRouteRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/borrowers': typeof AdminBorrowersRouteRouteWithChildren
  '/admin/deals': typeof AdminDealsRouteRouteWithChildren
  '/admin/listings': typeof AdminListingsRouteRouteWithChildren
  '/admin/mortgages': typeof AdminMortgagesRouteRouteWithChildren
  '/admin/obligations': typeof AdminObligationsRouteRouteWithChildren
  '/admin/properties': typeof AdminPropertiesRouteRouteWithChildren
  '/admin/underwriting': typeof AdminUnderwritingRouteRoute
  '/demo/amps': typeof DemoAmpsRouteRouteWithChildren
  '/demo/audit-traceability': typeof DemoAuditTraceabilityRouteRouteWithChildren
  '/demo/crm': typeof DemoCrmRouteRouteWithChildren
  '/demo/document-engine': typeof DemoDocumentEngineRouteRouteWithChildren
  '/demo/governed-transitions': typeof DemoGovernedTransitionsRouteRouteWithChildren
  '/demo/rbac': typeof DemoRbacRouteRouteWithChildren
  '/demo/rbac-auth': typeof DemoRbacAuthRouteRouteWithChildren
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/admin/$entitytype': typeof AdminEntitytypeRouteWithChildren
  '/demo/convex': typeof DemoConvexRoute
  '/demo/convex-action-cache': typeof DemoConvexActionCacheRoute
  '/demo/convex-aggregate': typeof DemoConvexAggregateRoute
  '/demo/convex-api-credentials': typeof DemoConvexApiCredentialsRoute
  '/demo/convex-audit-log': typeof DemoConvexAuditLogRoute
  '/demo/convex-cascading-delete': typeof DemoConvexCascadingDeleteRoute
  '/demo/convex-crons': typeof DemoConvexCronsRoute
  '/demo/convex-debouncer': typeof DemoConvexDebouncerRoute
  '/demo/convex-file-management': typeof DemoConvexFileManagementRoute
  '/demo/convex-fluent': typeof DemoConvexFluentRoute
  '/demo/convex-geospatial': typeof DemoConvexGeospatialRoute
  '/demo/convex-ledger': typeof DemoConvexLedgerRoute
  '/demo/convex-migrations': typeof DemoConvexMigrationsRoute
  '/demo/convex-presence': typeof DemoConvexPresenceRoute
  '/demo/convex-rate-limiter': typeof DemoConvexRateLimiterRoute
  '/demo/convex-timeline': typeof DemoConvexTimelineRoute
  '/demo/convex-tracer': typeof DemoConvexTracerRoute
  '/demo/convex-triggers': typeof DemoConvexTriggersRoute
  '/demo/convex-workflow': typeof DemoConvexWorkflowRoute
  '/demo/listings': typeof DemoListingsRoute
  '/demo/prod-ledger': typeof DemoProdLedgerRoute
  '/demo/simulation': typeof DemoSimulationRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/e2e/switch-org': typeof E2eSwitchOrgRoute
  '/demo/rbac/admin': typeof DemoRbacAdminRouteRouteWithChildren
  '/demo/rbac/borrower': typeof DemoRbacBorrowerRouteRoute
  '/demo/rbac/broker': typeof DemoRbacBrokerRouteRoute
  '/demo/rbac/lawyer': typeof DemoRbacLawyerRouteRoute
  '/demo/rbac/lender': typeof DemoRbacLenderRouteRoute
  '/admin/$entitytype/$recordid': typeof AdminEntitytypeRecordidRoute
  '/admin/borrowers/$recordid': typeof AdminBorrowersRecordidRoute
  '/admin/deals/$recordid': typeof AdminDealsRecordidRoute
  '/admin/listings/$recordid': typeof AdminListingsRecordidRoute
  '/admin/mortgages/$recordid': typeof AdminMortgagesRecordidRoute
  '/admin/obligations/$recordid': typeof AdminObligationsRecordidRoute
  '/admin/properties/$recordid': typeof AdminPropertiesRecordidRoute
  '/demo/amps/collection-attempts': typeof DemoAmpsCollectionAttemptsRoute
  '/demo/amps/collection-plan': typeof DemoAmpsCollectionPlanRoute
  '/demo/amps/e2e-payments': typeof DemoAmpsE2ePaymentsRoute
  '/demo/amps/rules': typeof DemoAmpsRulesRoute
  '/demo/audit-traceability/access-log': typeof DemoAuditTraceabilityAccessLogRoute
  '/demo/audit-traceability/audit-trail': typeof DemoAuditTraceabilityAuditTrailRoute
  '/demo/audit-traceability/hash-chain': typeof DemoAuditTraceabilityHashChainRoute
  '/demo/audit-traceability/pipeline': typeof DemoAuditTraceabilityPipelineRoute
  '/demo/audit-traceability/report': typeof DemoAuditTraceabilityReportRoute
  '/demo/crm/links': typeof DemoCrmLinksRoute
  '/demo/crm/system': typeof DemoCrmSystemRoute
  '/demo/document-engine/generate': typeof DemoDocumentEngineGenerateRoute
  '/demo/document-engine/groups': typeof DemoDocumentEngineGroupsRoute
  '/demo/document-engine/library': typeof DemoDocumentEngineLibraryRoute
  '/demo/document-engine/templates': typeof DemoDocumentEngineTemplatesRoute
  '/demo/document-engine/variables': typeof DemoDocumentEngineVariablesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/governed-transitions/journal': typeof DemoGovernedTransitionsJournalRoute
  '/demo/governed-transitions/machine': typeof DemoGovernedTransitionsMachineRoute
  '/demo/listings/$listingid': typeof DemoListingsListingidRoute
  '/demo/rbac-auth/access-control': typeof DemoRbacAuthAccessControlRoute
  '/demo/rbac-auth/audit': typeof DemoRbacAuthAuditRoute
  '/demo/rbac-auth/onboarding': typeof DemoRbacAuthOnboardingRoute
  '/demo/rbac-auth/roles': typeof DemoRbacAuthRolesRoute
  '/demo/amps/': typeof DemoAmpsIndexRoute
  '/demo/audit-traceability/': typeof DemoAuditTraceabilityIndexRoute
  '/demo/crm/': typeof DemoCrmIndexRoute
  '/demo/document-engine/': typeof DemoDocumentEngineIndexRoute
  '/demo/governed-transitions/': typeof DemoGovernedTransitionsIndexRoute
  '/demo/listings/': typeof DemoListingsIndexRoute
  '/demo/rbac-auth/': typeof DemoRbacAuthIndexRoute
  '/demo/rbac/': typeof DemoRbacIndexRoute
  '/demo/rbac/admin/underwriting': typeof DemoRbacAdminUnderwritingRouteRoute
  '/demo/crm/$objectDefId/$recordId': typeof DemoCrmObjectDefIdRecordIdRoute
  '/demo/document-engine/designer/$templateId': typeof DemoDocumentEngineDesignerTemplateIdRoute
  '/demo/amps/mortgages/$mortgageId/payments': typeof DemoAmpsMortgagesMortgageIdPaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/borrower'
    | '/broker'
    | '/lawyer'
    | '/lender'
    | '/onboard'
    | '/about'
    | '/callback'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/unauthorized'
    | '/admin/borrowers'
    | '/admin/deals'
    | '/admin/listings'
    | '/admin/mortgages'
    | '/admin/obligations'
    | '/admin/properties'
    | '/admin/underwriting'
    | '/demo/amps'
    | '/demo/audit-traceability'
    | '/demo/crm'
    | '/demo/document-engine'
    | '/demo/governed-transitions'
    | '/demo/rbac'
    | '/demo/rbac-auth'
    | '/authenticated'
    | '/admin/$entitytype'
    | '/demo/convex'
    | '/demo/convex-action-cache'
    | '/demo/convex-aggregate'
    | '/demo/convex-api-credentials'
    | '/demo/convex-audit-log'
    | '/demo/convex-cascading-delete'
    | '/demo/convex-crons'
    | '/demo/convex-debouncer'
    | '/demo/convex-file-management'
    | '/demo/convex-fluent'
    | '/demo/convex-geospatial'
    | '/demo/convex-ledger'
    | '/demo/convex-migrations'
    | '/demo/convex-presence'
    | '/demo/convex-rate-limiter'
    | '/demo/convex-timeline'
    | '/demo/convex-tracer'
    | '/demo/convex-triggers'
    | '/demo/convex-workflow'
    | '/demo/listings'
    | '/demo/prod-ledger'
    | '/demo/simulation'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/e2e/switch-org'
    | '/demo/rbac/admin'
    | '/demo/rbac/borrower'
    | '/demo/rbac/broker'
    | '/demo/rbac/lawyer'
    | '/demo/rbac/lender'
    | '/admin/$entitytype/$recordid'
    | '/admin/borrowers/$recordid'
    | '/admin/deals/$recordid'
    | '/admin/listings/$recordid'
    | '/admin/mortgages/$recordid'
    | '/admin/obligations/$recordid'
    | '/admin/properties/$recordid'
    | '/demo/amps/collection-attempts'
    | '/demo/amps/collection-plan'
    | '/demo/amps/e2e-payments'
    | '/demo/amps/rules'
    | '/demo/audit-traceability/access-log'
    | '/demo/audit-traceability/audit-trail'
    | '/demo/audit-traceability/hash-chain'
    | '/demo/audit-traceability/pipeline'
    | '/demo/audit-traceability/report'
    | '/demo/crm/links'
    | '/demo/crm/system'
    | '/demo/document-engine/generate'
    | '/demo/document-engine/groups'
    | '/demo/document-engine/library'
    | '/demo/document-engine/templates'
    | '/demo/document-engine/variables'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/governed-transitions/journal'
    | '/demo/governed-transitions/machine'
    | '/demo/listings/$listingid'
    | '/demo/rbac-auth/access-control'
    | '/demo/rbac-auth/audit'
    | '/demo/rbac-auth/onboarding'
    | '/demo/rbac-auth/roles'
    | '/demo/amps/'
    | '/demo/audit-traceability/'
    | '/demo/crm/'
    | '/demo/document-engine/'
    | '/demo/governed-transitions/'
    | '/demo/listings/'
    | '/demo/rbac-auth/'
    | '/demo/rbac/'
    | '/demo/rbac/admin/underwriting'
    | '/demo/crm/$objectDefId/$recordId'
    | '/demo/document-engine/designer/$templateId'
    | '/demo/amps/mortgages/$mortgageId/payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/borrower'
    | '/broker'
    | '/lawyer'
    | '/lender'
    | '/onboard'
    | '/about'
    | '/callback'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/unauthorized'
    | '/admin/borrowers'
    | '/admin/deals'
    | '/admin/listings'
    | '/admin/mortgages'
    | '/admin/obligations'
    | '/admin/properties'
    | '/admin/underwriting'
    | '/authenticated'
    | '/admin/$entitytype'
    | '/demo/convex'
    | '/demo/convex-action-cache'
    | '/demo/convex-aggregate'
    | '/demo/convex-api-credentials'
    | '/demo/convex-audit-log'
    | '/demo/convex-cascading-delete'
    | '/demo/convex-crons'
    | '/demo/convex-debouncer'
    | '/demo/convex-file-management'
    | '/demo/convex-fluent'
    | '/demo/convex-geospatial'
    | '/demo/convex-ledger'
    | '/demo/convex-migrations'
    | '/demo/convex-presence'
    | '/demo/convex-rate-limiter'
    | '/demo/convex-timeline'
    | '/demo/convex-tracer'
    | '/demo/convex-triggers'
    | '/demo/convex-workflow'
    | '/demo/listings'
    | '/demo/prod-ledger'
    | '/demo/simulation'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/e2e/switch-org'
    | '/demo/rbac/admin'
    | '/demo/rbac/borrower'
    | '/demo/rbac/broker'
    | '/demo/rbac/lawyer'
    | '/demo/rbac/lender'
    | '/admin/$entitytype/$recordid'
    | '/admin/borrowers/$recordid'
    | '/admin/deals/$recordid'
    | '/admin/listings/$recordid'
    | '/admin/mortgages/$recordid'
    | '/admin/obligations/$recordid'
    | '/admin/properties/$recordid'
    | '/demo/amps/collection-attempts'
    | '/demo/amps/collection-plan'
    | '/demo/amps/e2e-payments'
    | '/demo/amps/rules'
    | '/demo/audit-traceability/access-log'
    | '/demo/audit-traceability/audit-trail'
    | '/demo/audit-traceability/hash-chain'
    | '/demo/audit-traceability/pipeline'
    | '/demo/audit-traceability/report'
    | '/demo/crm/links'
    | '/demo/crm/system'
    | '/demo/document-engine/generate'
    | '/demo/document-engine/groups'
    | '/demo/document-engine/library'
    | '/demo/document-engine/templates'
    | '/demo/document-engine/variables'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/governed-transitions/journal'
    | '/demo/governed-transitions/machine'
    | '/demo/listings/$listingid'
    | '/demo/rbac-auth/access-control'
    | '/demo/rbac-auth/audit'
    | '/demo/rbac-auth/onboarding'
    | '/demo/rbac-auth/roles'
    | '/demo/amps'
    | '/demo/audit-traceability'
    | '/demo/crm'
    | '/demo/document-engine'
    | '/demo/governed-transitions'
    | '/demo/listings'
    | '/demo/rbac-auth'
    | '/demo/rbac'
    | '/demo/rbac/admin/underwriting'
    | '/demo/crm/$objectDefId/$recordId'
    | '/demo/document-engine/designer/$templateId'
    | '/demo/amps/mortgages/$mortgageId/payments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/borrower'
    | '/broker'
    | '/lawyer'
    | '/lender'
    | '/onboard'
    | '/about'
    | '/callback'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/unauthorized'
    | '/admin/borrowers'
    | '/admin/deals'
    | '/admin/listings'
    | '/admin/mortgages'
    | '/admin/obligations'
    | '/admin/properties'
    | '/admin/underwriting'
    | '/demo/amps'
    | '/demo/audit-traceability'
    | '/demo/crm'
    | '/demo/document-engine'
    | '/demo/governed-transitions'
    | '/demo/rbac'
    | '/demo/rbac-auth'
    | '/_authenticated/authenticated'
    | '/admin/$entitytype'
    | '/demo/convex'
    | '/demo/convex-action-cache'
    | '/demo/convex-aggregate'
    | '/demo/convex-api-credentials'
    | '/demo/convex-audit-log'
    | '/demo/convex-cascading-delete'
    | '/demo/convex-crons'
    | '/demo/convex-debouncer'
    | '/demo/convex-file-management'
    | '/demo/convex-fluent'
    | '/demo/convex-geospatial'
    | '/demo/convex-ledger'
    | '/demo/convex-migrations'
    | '/demo/convex-presence'
    | '/demo/convex-rate-limiter'
    | '/demo/convex-timeline'
    | '/demo/convex-tracer'
    | '/demo/convex-triggers'
    | '/demo/convex-workflow'
    | '/demo/listings'
    | '/demo/prod-ledger'
    | '/demo/simulation'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/e2e/switch-org'
    | '/demo/rbac/admin'
    | '/demo/rbac/borrower'
    | '/demo/rbac/broker'
    | '/demo/rbac/lawyer'
    | '/demo/rbac/lender'
    | '/admin/$entitytype/$recordid'
    | '/admin/borrowers/$recordid'
    | '/admin/deals/$recordid'
    | '/admin/listings/$recordid'
    | '/admin/mortgages/$recordid'
    | '/admin/obligations/$recordid'
    | '/admin/properties/$recordid'
    | '/demo/amps/collection-attempts'
    | '/demo/amps/collection-plan'
    | '/demo/amps/e2e-payments'
    | '/demo/amps/rules'
    | '/demo/audit-traceability/access-log'
    | '/demo/audit-traceability/audit-trail'
    | '/demo/audit-traceability/hash-chain'
    | '/demo/audit-traceability/pipeline'
    | '/demo/audit-traceability/report'
    | '/demo/crm/links'
    | '/demo/crm/system'
    | '/demo/document-engine/generate'
    | '/demo/document-engine/groups'
    | '/demo/document-engine/library'
    | '/demo/document-engine/templates'
    | '/demo/document-engine/variables'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/governed-transitions/journal'
    | '/demo/governed-transitions/machine'
    | '/demo/listings/$listingid'
    | '/demo/rbac-auth/access-control'
    | '/demo/rbac-auth/audit'
    | '/demo/rbac-auth/onboarding'
    | '/demo/rbac-auth/roles'
    | '/demo/amps/'
    | '/demo/audit-traceability/'
    | '/demo/crm/'
    | '/demo/document-engine/'
    | '/demo/governed-transitions/'
    | '/demo/listings/'
    | '/demo/rbac-auth/'
    | '/demo/rbac/'
    | '/demo/rbac/admin/underwriting'
    | '/demo/crm/$objectDefId/$recordId'
    | '/demo/document-engine/designer/$templateId'
    | '/demo/amps/mortgages/$mortgageId/payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BorrowerRouteRoute: typeof BorrowerRouteRoute
  BrokerRouteRoute: typeof BrokerRouteRoute
  LawyerRouteRoute: typeof LawyerRouteRoute
  LenderRouteRoute: typeof LenderRouteRoute
  OnboardRouteRoute: typeof OnboardRouteRoute
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  SignUpRoute: typeof SignUpRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DemoAmpsRouteRoute: typeof DemoAmpsRouteRouteWithChildren
  DemoAuditTraceabilityRouteRoute: typeof DemoAuditTraceabilityRouteRouteWithChildren
  DemoCrmRouteRoute: typeof DemoCrmRouteRouteWithChildren
  DemoDocumentEngineRouteRoute: typeof DemoDocumentEngineRouteRouteWithChildren
  DemoGovernedTransitionsRouteRoute: typeof DemoGovernedTransitionsRouteRouteWithChildren
  DemoRbacRouteRoute: typeof DemoRbacRouteRouteWithChildren
  DemoRbacAuthRouteRoute: typeof DemoRbacAuthRouteRouteWithChildren
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoConvexActionCacheRoute: typeof DemoConvexActionCacheRoute
  DemoConvexAggregateRoute: typeof DemoConvexAggregateRoute
  DemoConvexApiCredentialsRoute: typeof DemoConvexApiCredentialsRoute
  DemoConvexAuditLogRoute: typeof DemoConvexAuditLogRoute
  DemoConvexCascadingDeleteRoute: typeof DemoConvexCascadingDeleteRoute
  DemoConvexCronsRoute: typeof DemoConvexCronsRoute
  DemoConvexDebouncerRoute: typeof DemoConvexDebouncerRoute
  DemoConvexFileManagementRoute: typeof DemoConvexFileManagementRoute
  DemoConvexFluentRoute: typeof DemoConvexFluentRoute
  DemoConvexGeospatialRoute: typeof DemoConvexGeospatialRoute
  DemoConvexLedgerRoute: typeof DemoConvexLedgerRoute
  DemoConvexMigrationsRoute: typeof DemoConvexMigrationsRoute
  DemoConvexPresenceRoute: typeof DemoConvexPresenceRoute
  DemoConvexRateLimiterRoute: typeof DemoConvexRateLimiterRoute
  DemoConvexTimelineRoute: typeof DemoConvexTimelineRoute
  DemoConvexTracerRoute: typeof DemoConvexTracerRoute
  DemoConvexTriggersRoute: typeof DemoConvexTriggersRoute
  DemoConvexWorkflowRoute: typeof DemoConvexWorkflowRoute
  DemoListingsRoute: typeof DemoListingsRoute
  DemoProdLedgerRoute: typeof DemoProdLedgerRoute
  DemoSimulationRoute: typeof DemoSimulationRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  E2eSwitchOrgRoute: typeof E2eSwitchOrgRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoListingsListingidRoute: typeof DemoListingsListingidRoute
  DemoListingsIndexRoute: typeof DemoListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender': {
      id: '/lender'
      path: '/lender'
      fullPath: '/lender'
      preLoaderRoute: typeof LenderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer': {
      id: '/lawyer'
      path: '/lawyer'
      fullPath: '/lawyer'
      preLoaderRoute: typeof LawyerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrower': {
      id: '/borrower'
      path: '/borrower'
      fullPath: '/borrower'
      preLoaderRoute: typeof BorrowerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/switch-org': {
      id: '/e2e/switch-org'
      path: '/e2e/switch-org'
      fullPath: '/e2e/switch-org'
      preLoaderRoute: typeof E2eSwitchOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/simulation': {
      id: '/demo/simulation'
      path: '/demo/simulation'
      fullPath: '/demo/simulation'
      preLoaderRoute: typeof DemoSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prod-ledger': {
      id: '/demo/prod-ledger'
      path: '/demo/prod-ledger'
      fullPath: '/demo/prod-ledger'
      preLoaderRoute: typeof DemoProdLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/listings': {
      id: '/demo/listings'
      path: '/demo/listings'
      fullPath: '/demo/listings'
      preLoaderRoute: typeof DemoListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-workflow': {
      id: '/demo/convex-workflow'
      path: '/demo/convex-workflow'
      fullPath: '/demo/convex-workflow'
      preLoaderRoute: typeof DemoConvexWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-triggers': {
      id: '/demo/convex-triggers'
      path: '/demo/convex-triggers'
      fullPath: '/demo/convex-triggers'
      preLoaderRoute: typeof DemoConvexTriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-tracer': {
      id: '/demo/convex-tracer'
      path: '/demo/convex-tracer'
      fullPath: '/demo/convex-tracer'
      preLoaderRoute: typeof DemoConvexTracerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-timeline': {
      id: '/demo/convex-timeline'
      path: '/demo/convex-timeline'
      fullPath: '/demo/convex-timeline'
      preLoaderRoute: typeof DemoConvexTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-rate-limiter': {
      id: '/demo/convex-rate-limiter'
      path: '/demo/convex-rate-limiter'
      fullPath: '/demo/convex-rate-limiter'
      preLoaderRoute: typeof DemoConvexRateLimiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-presence': {
      id: '/demo/convex-presence'
      path: '/demo/convex-presence'
      fullPath: '/demo/convex-presence'
      preLoaderRoute: typeof DemoConvexPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-migrations': {
      id: '/demo/convex-migrations'
      path: '/demo/convex-migrations'
      fullPath: '/demo/convex-migrations'
      preLoaderRoute: typeof DemoConvexMigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-ledger': {
      id: '/demo/convex-ledger'
      path: '/demo/convex-ledger'
      fullPath: '/demo/convex-ledger'
      preLoaderRoute: typeof DemoConvexLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-geospatial': {
      id: '/demo/convex-geospatial'
      path: '/demo/convex-geospatial'
      fullPath: '/demo/convex-geospatial'
      preLoaderRoute: typeof DemoConvexGeospatialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-fluent': {
      id: '/demo/convex-fluent'
      path: '/demo/convex-fluent'
      fullPath: '/demo/convex-fluent'
      preLoaderRoute: typeof DemoConvexFluentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-file-management': {
      id: '/demo/convex-file-management'
      path: '/demo/convex-file-management'
      fullPath: '/demo/convex-file-management'
      preLoaderRoute: typeof DemoConvexFileManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-debouncer': {
      id: '/demo/convex-debouncer'
      path: '/demo/convex-debouncer'
      fullPath: '/demo/convex-debouncer'
      preLoaderRoute: typeof DemoConvexDebouncerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-crons': {
      id: '/demo/convex-crons'
      path: '/demo/convex-crons'
      fullPath: '/demo/convex-crons'
      preLoaderRoute: typeof DemoConvexCronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-cascading-delete': {
      id: '/demo/convex-cascading-delete'
      path: '/demo/convex-cascading-delete'
      fullPath: '/demo/convex-cascading-delete'
      preLoaderRoute: typeof DemoConvexCascadingDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-audit-log': {
      id: '/demo/convex-audit-log'
      path: '/demo/convex-audit-log'
      fullPath: '/demo/convex-audit-log'
      preLoaderRoute: typeof DemoConvexAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-api-credentials': {
      id: '/demo/convex-api-credentials'
      path: '/demo/convex-api-credentials'
      fullPath: '/demo/convex-api-credentials'
      preLoaderRoute: typeof DemoConvexApiCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-aggregate': {
      id: '/demo/convex-aggregate'
      path: '/demo/convex-aggregate'
      fullPath: '/demo/convex-aggregate'
      preLoaderRoute: typeof DemoConvexAggregateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex-action-cache': {
      id: '/demo/convex-action-cache'
      path: '/demo/convex-action-cache'
      fullPath: '/demo/convex-action-cache'
      preLoaderRoute: typeof DemoConvexActionCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$entitytype': {
      id: '/admin/$entitytype'
      path: '/$entitytype'
      fullPath: '/admin/$entitytype'
      preLoaderRoute: typeof AdminEntitytypeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rbac-auth': {
      id: '/demo/rbac-auth'
      path: '/demo/rbac-auth'
      fullPath: '/demo/rbac-auth'
      preLoaderRoute: typeof DemoRbacAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rbac': {
      id: '/demo/rbac'
      path: '/demo/rbac'
      fullPath: '/demo/rbac'
      preLoaderRoute: typeof DemoRbacRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/governed-transitions': {
      id: '/demo/governed-transitions'
      path: '/demo/governed-transitions'
      fullPath: '/demo/governed-transitions'
      preLoaderRoute: typeof DemoGovernedTransitionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/document-engine': {
      id: '/demo/document-engine'
      path: '/demo/document-engine'
      fullPath: '/demo/document-engine'
      preLoaderRoute: typeof DemoDocumentEngineRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/crm': {
      id: '/demo/crm'
      path: '/demo/crm'
      fullPath: '/demo/crm'
      preLoaderRoute: typeof DemoCrmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/audit-traceability': {
      id: '/demo/audit-traceability'
      path: '/demo/audit-traceability'
      fullPath: '/demo/audit-traceability'
      preLoaderRoute: typeof DemoAuditTraceabilityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/amps': {
      id: '/demo/amps'
      path: '/demo/amps'
      fullPath: '/demo/amps'
      preLoaderRoute: typeof DemoAmpsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/underwriting': {
      id: '/admin/underwriting'
      path: '/underwriting'
      fullPath: '/admin/underwriting'
      preLoaderRoute: typeof AdminUnderwritingRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/obligations': {
      id: '/admin/obligations'
      path: '/obligations'
      fullPath: '/admin/obligations'
      preLoaderRoute: typeof AdminObligationsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mortgages': {
      id: '/admin/mortgages'
      path: '/mortgages'
      fullPath: '/admin/mortgages'
      preLoaderRoute: typeof AdminMortgagesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/borrowers': {
      id: '/admin/borrowers'
      path: '/borrowers'
      fullPath: '/admin/borrowers'
      preLoaderRoute: typeof AdminBorrowersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/rbac/': {
      id: '/demo/rbac/'
      path: '/'
      fullPath: '/demo/rbac/'
      preLoaderRoute: typeof DemoRbacIndexRouteImport
      parentRoute: typeof DemoRbacRouteRoute
    }
    '/demo/rbac-auth/': {
      id: '/demo/rbac-auth/'
      path: '/'
      fullPath: '/demo/rbac-auth/'
      preLoaderRoute: typeof DemoRbacAuthIndexRouteImport
      parentRoute: typeof DemoRbacAuthRouteRoute
    }
    '/demo/listings/': {
      id: '/demo/listings/'
      path: '/demo/listings'
      fullPath: '/demo/listings/'
      preLoaderRoute: typeof DemoListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/governed-transitions/': {
      id: '/demo/governed-transitions/'
      path: '/'
      fullPath: '/demo/governed-transitions/'
      preLoaderRoute: typeof DemoGovernedTransitionsIndexRouteImport
      parentRoute: typeof DemoGovernedTransitionsRouteRoute
    }
    '/demo/document-engine/': {
      id: '/demo/document-engine/'
      path: '/'
      fullPath: '/demo/document-engine/'
      preLoaderRoute: typeof DemoDocumentEngineIndexRouteImport
      parentRoute: typeof DemoDocumentEngineRouteRoute
    }
    '/demo/crm/': {
      id: '/demo/crm/'
      path: '/'
      fullPath: '/demo/crm/'
      preLoaderRoute: typeof DemoCrmIndexRouteImport
      parentRoute: typeof DemoCrmRouteRoute
    }
    '/demo/audit-traceability/': {
      id: '/demo/audit-traceability/'
      path: '/'
      fullPath: '/demo/audit-traceability/'
      preLoaderRoute: typeof DemoAuditTraceabilityIndexRouteImport
      parentRoute: typeof DemoAuditTraceabilityRouteRoute
    }
    '/demo/amps/': {
      id: '/demo/amps/'
      path: '/'
      fullPath: '/demo/amps/'
      preLoaderRoute: typeof DemoAmpsIndexRouteImport
      parentRoute: typeof DemoAmpsRouteRoute
    }
    '/demo/rbac-auth/roles': {
      id: '/demo/rbac-auth/roles'
      path: '/roles'
      fullPath: '/demo/rbac-auth/roles'
      preLoaderRoute: typeof DemoRbacAuthRolesRouteImport
      parentRoute: typeof DemoRbacAuthRouteRoute
    }
    '/demo/rbac-auth/onboarding': {
      id: '/demo/rbac-auth/onboarding'
      path: '/onboarding'
      fullPath: '/demo/rbac-auth/onboarding'
      preLoaderRoute: typeof DemoRbacAuthOnboardingRouteImport
      parentRoute: typeof DemoRbacAuthRouteRoute
    }
    '/demo/rbac-auth/audit': {
      id: '/demo/rbac-auth/audit'
      path: '/audit'
      fullPath: '/demo/rbac-auth/audit'
      preLoaderRoute: typeof DemoRbacAuthAuditRouteImport
      parentRoute: typeof DemoRbacAuthRouteRoute
    }
    '/demo/rbac-auth/access-control': {
      id: '/demo/rbac-auth/access-control'
      path: '/access-control'
      fullPath: '/demo/rbac-auth/access-control'
      preLoaderRoute: typeof DemoRbacAuthAccessControlRouteImport
      parentRoute: typeof DemoRbacAuthRouteRoute
    }
    '/demo/listings/$listingid': {
      id: '/demo/listings/$listingid'
      path: '/demo/listings/$listingid'
      fullPath: '/demo/listings/$listingid'
      preLoaderRoute: typeof DemoListingsListingidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/governed-transitions/machine': {
      id: '/demo/governed-transitions/machine'
      path: '/machine'
      fullPath: '/demo/governed-transitions/machine'
      preLoaderRoute: typeof DemoGovernedTransitionsMachineRouteImport
      parentRoute: typeof DemoGovernedTransitionsRouteRoute
    }
    '/demo/governed-transitions/journal': {
      id: '/demo/governed-transitions/journal'
      path: '/journal'
      fullPath: '/demo/governed-transitions/journal'
      preLoaderRoute: typeof DemoGovernedTransitionsJournalRouteImport
      parentRoute: typeof DemoGovernedTransitionsRouteRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/document-engine/variables': {
      id: '/demo/document-engine/variables'
      path: '/variables'
      fullPath: '/demo/document-engine/variables'
      preLoaderRoute: typeof DemoDocumentEngineVariablesRouteImport
      parentRoute: typeof DemoDocumentEngineRouteRoute
    }
    '/demo/document-engine/templates': {
      id: '/demo/document-engine/templates'
      path: '/templates'
      fullPath: '/demo/document-engine/templates'
      preLoaderRoute: typeof DemoDocumentEngineTemplatesRouteImport
      parentRoute: typeof DemoDocumentEngineRouteRoute
    }
    '/demo/document-engine/library': {
      id: '/demo/document-engine/library'
      path: '/library'
      fullPath: '/demo/document-engine/library'
      preLoaderRoute: typeof DemoDocumentEngineLibraryRouteImport
      parentRoute: typeof DemoDocumentEngineRouteRoute
    }
    '/demo/document-engine/groups': {
      id: '/demo/document-engine/groups'
      path: '/groups'
      fullPath: '/demo/document-engine/groups'
      preLoaderRoute: typeof DemoDocumentEngineGroupsRouteImport
      parentRoute: typeof DemoDocumentEngineRouteRoute
    }
    '/demo/document-engine/generate': {
      id: '/demo/document-engine/generate'
      path: '/generate'
      fullPath: '/demo/document-engine/generate'
      preLoaderRoute: typeof DemoDocumentEngineGenerateRouteImport
      parentRoute: typeof DemoDocumentEngineRouteRoute
    }
    '/demo/crm/system': {
      id: '/demo/crm/system'
      path: '/system'
      fullPath: '/demo/crm/system'
      preLoaderRoute: typeof DemoCrmSystemRouteImport
      parentRoute: typeof DemoCrmRouteRoute
    }
    '/demo/crm/links': {
      id: '/demo/crm/links'
      path: '/links'
      fullPath: '/demo/crm/links'
      preLoaderRoute: typeof DemoCrmLinksRouteImport
      parentRoute: typeof DemoCrmRouteRoute
    }
    '/demo/audit-traceability/report': {
      id: '/demo/audit-traceability/report'
      path: '/report'
      fullPath: '/demo/audit-traceability/report'
      preLoaderRoute: typeof DemoAuditTraceabilityReportRouteImport
      parentRoute: typeof DemoAuditTraceabilityRouteRoute
    }
    '/demo/audit-traceability/pipeline': {
      id: '/demo/audit-traceability/pipeline'
      path: '/pipeline'
      fullPath: '/demo/audit-traceability/pipeline'
      preLoaderRoute: typeof DemoAuditTraceabilityPipelineRouteImport
      parentRoute: typeof DemoAuditTraceabilityRouteRoute
    }
    '/demo/audit-traceability/hash-chain': {
      id: '/demo/audit-traceability/hash-chain'
      path: '/hash-chain'
      fullPath: '/demo/audit-traceability/hash-chain'
      preLoaderRoute: typeof DemoAuditTraceabilityHashChainRouteImport
      parentRoute: typeof DemoAuditTraceabilityRouteRoute
    }
    '/demo/audit-traceability/audit-trail': {
      id: '/demo/audit-traceability/audit-trail'
      path: '/audit-trail'
      fullPath: '/demo/audit-traceability/audit-trail'
      preLoaderRoute: typeof DemoAuditTraceabilityAuditTrailRouteImport
      parentRoute: typeof DemoAuditTraceabilityRouteRoute
    }
    '/demo/audit-traceability/access-log': {
      id: '/demo/audit-traceability/access-log'
      path: '/access-log'
      fullPath: '/demo/audit-traceability/access-log'
      preLoaderRoute: typeof DemoAuditTraceabilityAccessLogRouteImport
      parentRoute: typeof DemoAuditTraceabilityRouteRoute
    }
    '/demo/amps/rules': {
      id: '/demo/amps/rules'
      path: '/rules'
      fullPath: '/demo/amps/rules'
      preLoaderRoute: typeof DemoAmpsRulesRouteImport
      parentRoute: typeof DemoAmpsRouteRoute
    }
    '/demo/amps/e2e-payments': {
      id: '/demo/amps/e2e-payments'
      path: '/e2e-payments'
      fullPath: '/demo/amps/e2e-payments'
      preLoaderRoute: typeof DemoAmpsE2ePaymentsRouteImport
      parentRoute: typeof DemoAmpsRouteRoute
    }
    '/demo/amps/collection-plan': {
      id: '/demo/amps/collection-plan'
      path: '/collection-plan'
      fullPath: '/demo/amps/collection-plan'
      preLoaderRoute: typeof DemoAmpsCollectionPlanRouteImport
      parentRoute: typeof DemoAmpsRouteRoute
    }
    '/demo/amps/collection-attempts': {
      id: '/demo/amps/collection-attempts'
      path: '/collection-attempts'
      fullPath: '/demo/amps/collection-attempts'
      preLoaderRoute: typeof DemoAmpsCollectionAttemptsRouteImport
      parentRoute: typeof DemoAmpsRouteRoute
    }
    '/admin/properties/$recordid': {
      id: '/admin/properties/$recordid'
      path: '/$recordid'
      fullPath: '/admin/properties/$recordid'
      preLoaderRoute: typeof AdminPropertiesRecordidRouteImport
      parentRoute: typeof AdminPropertiesRouteRoute
    }
    '/admin/obligations/$recordid': {
      id: '/admin/obligations/$recordid'
      path: '/$recordid'
      fullPath: '/admin/obligations/$recordid'
      preLoaderRoute: typeof AdminObligationsRecordidRouteImport
      parentRoute: typeof AdminObligationsRouteRoute
    }
    '/admin/mortgages/$recordid': {
      id: '/admin/mortgages/$recordid'
      path: '/$recordid'
      fullPath: '/admin/mortgages/$recordid'
      preLoaderRoute: typeof AdminMortgagesRecordidRouteImport
      parentRoute: typeof AdminMortgagesRouteRoute
    }
    '/admin/listings/$recordid': {
      id: '/admin/listings/$recordid'
      path: '/$recordid'
      fullPath: '/admin/listings/$recordid'
      preLoaderRoute: typeof AdminListingsRecordidRouteImport
      parentRoute: typeof AdminListingsRouteRoute
    }
    '/admin/deals/$recordid': {
      id: '/admin/deals/$recordid'
      path: '/$recordid'
      fullPath: '/admin/deals/$recordid'
      preLoaderRoute: typeof AdminDealsRecordidRouteImport
      parentRoute: typeof AdminDealsRouteRoute
    }
    '/admin/borrowers/$recordid': {
      id: '/admin/borrowers/$recordid'
      path: '/$recordid'
      fullPath: '/admin/borrowers/$recordid'
      preLoaderRoute: typeof AdminBorrowersRecordidRouteImport
      parentRoute: typeof AdminBorrowersRouteRoute
    }
    '/admin/$entitytype/$recordid': {
      id: '/admin/$entitytype/$recordid'
      path: '/$recordid'
      fullPath: '/admin/$entitytype/$recordid'
      preLoaderRoute: typeof AdminEntitytypeRecordidRouteImport
      parentRoute: typeof AdminEntitytypeRoute
    }
    '/demo/rbac/lender': {
      id: '/demo/rbac/lender'
      path: '/lender'
      fullPath: '/demo/rbac/lender'
      preLoaderRoute: typeof DemoRbacLenderRouteRouteImport
      parentRoute: typeof DemoRbacRouteRoute
    }
    '/demo/rbac/lawyer': {
      id: '/demo/rbac/lawyer'
      path: '/lawyer'
      fullPath: '/demo/rbac/lawyer'
      preLoaderRoute: typeof DemoRbacLawyerRouteRouteImport
      parentRoute: typeof DemoRbacRouteRoute
    }
    '/demo/rbac/broker': {
      id: '/demo/rbac/broker'
      path: '/broker'
      fullPath: '/demo/rbac/broker'
      preLoaderRoute: typeof DemoRbacBrokerRouteRouteImport
      parentRoute: typeof DemoRbacRouteRoute
    }
    '/demo/rbac/borrower': {
      id: '/demo/rbac/borrower'
      path: '/borrower'
      fullPath: '/demo/rbac/borrower'
      preLoaderRoute: typeof DemoRbacBorrowerRouteRouteImport
      parentRoute: typeof DemoRbacRouteRoute
    }
    '/demo/rbac/admin': {
      id: '/demo/rbac/admin'
      path: '/admin'
      fullPath: '/demo/rbac/admin'
      preLoaderRoute: typeof DemoRbacAdminRouteRouteImport
      parentRoute: typeof DemoRbacRouteRoute
    }
    '/demo/document-engine/designer/$templateId': {
      id: '/demo/document-engine/designer/$templateId'
      path: '/designer/$templateId'
      fullPath: '/demo/document-engine/designer/$templateId'
      preLoaderRoute: typeof DemoDocumentEngineDesignerTemplateIdRouteImport
      parentRoute: typeof DemoDocumentEngineRouteRoute
    }
    '/demo/crm/$objectDefId/$recordId': {
      id: '/demo/crm/$objectDefId/$recordId'
      path: '/$objectDefId/$recordId'
      fullPath: '/demo/crm/$objectDefId/$recordId'
      preLoaderRoute: typeof DemoCrmObjectDefIdRecordIdRouteImport
      parentRoute: typeof DemoCrmRouteRoute
    }
    '/demo/rbac/admin/underwriting': {
      id: '/demo/rbac/admin/underwriting'
      path: '/underwriting'
      fullPath: '/demo/rbac/admin/underwriting'
      preLoaderRoute: typeof DemoRbacAdminUnderwritingRouteRouteImport
      parentRoute: typeof DemoRbacAdminRouteRoute
    }
    '/demo/amps/mortgages/$mortgageId/payments': {
      id: '/demo/amps/mortgages/$mortgageId/payments'
      path: '/mortgages/$mortgageId/payments'
      fullPath: '/demo/amps/mortgages/$mortgageId/payments'
      preLoaderRoute: typeof DemoAmpsMortgagesMortgageIdPaymentsRouteImport
      parentRoute: typeof DemoAmpsRouteRoute
    }
  }
}

interface AdminBorrowersRouteRouteChildren {
  AdminBorrowersRecordidRoute: typeof AdminBorrowersRecordidRoute
}

const AdminBorrowersRouteRouteChildren: AdminBorrowersRouteRouteChildren = {
  AdminBorrowersRecordidRoute: AdminBorrowersRecordidRoute,
}

const AdminBorrowersRouteRouteWithChildren =
  AdminBorrowersRouteRoute._addFileChildren(AdminBorrowersRouteRouteChildren)

interface AdminDealsRouteRouteChildren {
  AdminDealsRecordidRoute: typeof AdminDealsRecordidRoute
}

const AdminDealsRouteRouteChildren: AdminDealsRouteRouteChildren = {
  AdminDealsRecordidRoute: AdminDealsRecordidRoute,
}

const AdminDealsRouteRouteWithChildren = AdminDealsRouteRoute._addFileChildren(
  AdminDealsRouteRouteChildren,
)

interface AdminListingsRouteRouteChildren {
  AdminListingsRecordidRoute: typeof AdminListingsRecordidRoute
}

const AdminListingsRouteRouteChildren: AdminListingsRouteRouteChildren = {
  AdminListingsRecordidRoute: AdminListingsRecordidRoute,
}

const AdminListingsRouteRouteWithChildren =
  AdminListingsRouteRoute._addFileChildren(AdminListingsRouteRouteChildren)

interface AdminMortgagesRouteRouteChildren {
  AdminMortgagesRecordidRoute: typeof AdminMortgagesRecordidRoute
}

const AdminMortgagesRouteRouteChildren: AdminMortgagesRouteRouteChildren = {
  AdminMortgagesRecordidRoute: AdminMortgagesRecordidRoute,
}

const AdminMortgagesRouteRouteWithChildren =
  AdminMortgagesRouteRoute._addFileChildren(AdminMortgagesRouteRouteChildren)

interface AdminObligationsRouteRouteChildren {
  AdminObligationsRecordidRoute: typeof AdminObligationsRecordidRoute
}

const AdminObligationsRouteRouteChildren: AdminObligationsRouteRouteChildren = {
  AdminObligationsRecordidRoute: AdminObligationsRecordidRoute,
}

const AdminObligationsRouteRouteWithChildren =
  AdminObligationsRouteRoute._addFileChildren(
    AdminObligationsRouteRouteChildren,
  )

interface AdminPropertiesRouteRouteChildren {
  AdminPropertiesRecordidRoute: typeof AdminPropertiesRecordidRoute
}

const AdminPropertiesRouteRouteChildren: AdminPropertiesRouteRouteChildren = {
  AdminPropertiesRecordidRoute: AdminPropertiesRecordidRoute,
}

const AdminPropertiesRouteRouteWithChildren =
  AdminPropertiesRouteRoute._addFileChildren(AdminPropertiesRouteRouteChildren)

interface AdminEntitytypeRouteChildren {
  AdminEntitytypeRecordidRoute: typeof AdminEntitytypeRecordidRoute
}

const AdminEntitytypeRouteChildren: AdminEntitytypeRouteChildren = {
  AdminEntitytypeRecordidRoute: AdminEntitytypeRecordidRoute,
}

const AdminEntitytypeRouteWithChildren = AdminEntitytypeRoute._addFileChildren(
  AdminEntitytypeRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBorrowersRouteRoute: typeof AdminBorrowersRouteRouteWithChildren
  AdminDealsRouteRoute: typeof AdminDealsRouteRouteWithChildren
  AdminListingsRouteRoute: typeof AdminListingsRouteRouteWithChildren
  AdminMortgagesRouteRoute: typeof AdminMortgagesRouteRouteWithChildren
  AdminObligationsRouteRoute: typeof AdminObligationsRouteRouteWithChildren
  AdminPropertiesRouteRoute: typeof AdminPropertiesRouteRouteWithChildren
  AdminUnderwritingRouteRoute: typeof AdminUnderwritingRouteRoute
  AdminEntitytypeRoute: typeof AdminEntitytypeRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBorrowersRouteRoute: AdminBorrowersRouteRouteWithChildren,
  AdminDealsRouteRoute: AdminDealsRouteRouteWithChildren,
  AdminListingsRouteRoute: AdminListingsRouteRouteWithChildren,
  AdminMortgagesRouteRoute: AdminMortgagesRouteRouteWithChildren,
  AdminObligationsRouteRoute: AdminObligationsRouteRouteWithChildren,
  AdminPropertiesRouteRoute: AdminPropertiesRouteRouteWithChildren,
  AdminUnderwritingRouteRoute: AdminUnderwritingRouteRoute,
  AdminEntitytypeRoute: AdminEntitytypeRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DemoAmpsRouteRouteChildren {
  DemoAmpsCollectionAttemptsRoute: typeof DemoAmpsCollectionAttemptsRoute
  DemoAmpsCollectionPlanRoute: typeof DemoAmpsCollectionPlanRoute
  DemoAmpsE2ePaymentsRoute: typeof DemoAmpsE2ePaymentsRoute
  DemoAmpsRulesRoute: typeof DemoAmpsRulesRoute
  DemoAmpsIndexRoute: typeof DemoAmpsIndexRoute
  DemoAmpsMortgagesMortgageIdPaymentsRoute: typeof DemoAmpsMortgagesMortgageIdPaymentsRoute
}

const DemoAmpsRouteRouteChildren: DemoAmpsRouteRouteChildren = {
  DemoAmpsCollectionAttemptsRoute: DemoAmpsCollectionAttemptsRoute,
  DemoAmpsCollectionPlanRoute: DemoAmpsCollectionPlanRoute,
  DemoAmpsE2ePaymentsRoute: DemoAmpsE2ePaymentsRoute,
  DemoAmpsRulesRoute: DemoAmpsRulesRoute,
  DemoAmpsIndexRoute: DemoAmpsIndexRoute,
  DemoAmpsMortgagesMortgageIdPaymentsRoute:
    DemoAmpsMortgagesMortgageIdPaymentsRoute,
}

const DemoAmpsRouteRouteWithChildren = DemoAmpsRouteRoute._addFileChildren(
  DemoAmpsRouteRouteChildren,
)

interface DemoAuditTraceabilityRouteRouteChildren {
  DemoAuditTraceabilityAccessLogRoute: typeof DemoAuditTraceabilityAccessLogRoute
  DemoAuditTraceabilityAuditTrailRoute: typeof DemoAuditTraceabilityAuditTrailRoute
  DemoAuditTraceabilityHashChainRoute: typeof DemoAuditTraceabilityHashChainRoute
  DemoAuditTraceabilityPipelineRoute: typeof DemoAuditTraceabilityPipelineRoute
  DemoAuditTraceabilityReportRoute: typeof DemoAuditTraceabilityReportRoute
  DemoAuditTraceabilityIndexRoute: typeof DemoAuditTraceabilityIndexRoute
}

const DemoAuditTraceabilityRouteRouteChildren: DemoAuditTraceabilityRouteRouteChildren =
  {
    DemoAuditTraceabilityAccessLogRoute: DemoAuditTraceabilityAccessLogRoute,
    DemoAuditTraceabilityAuditTrailRoute: DemoAuditTraceabilityAuditTrailRoute,
    DemoAuditTraceabilityHashChainRoute: DemoAuditTraceabilityHashChainRoute,
    DemoAuditTraceabilityPipelineRoute: DemoAuditTraceabilityPipelineRoute,
    DemoAuditTraceabilityReportRoute: DemoAuditTraceabilityReportRoute,
    DemoAuditTraceabilityIndexRoute: DemoAuditTraceabilityIndexRoute,
  }

const DemoAuditTraceabilityRouteRouteWithChildren =
  DemoAuditTraceabilityRouteRoute._addFileChildren(
    DemoAuditTraceabilityRouteRouteChildren,
  )

interface DemoCrmRouteRouteChildren {
  DemoCrmLinksRoute: typeof DemoCrmLinksRoute
  DemoCrmSystemRoute: typeof DemoCrmSystemRoute
  DemoCrmIndexRoute: typeof DemoCrmIndexRoute
  DemoCrmObjectDefIdRecordIdRoute: typeof DemoCrmObjectDefIdRecordIdRoute
}

const DemoCrmRouteRouteChildren: DemoCrmRouteRouteChildren = {
  DemoCrmLinksRoute: DemoCrmLinksRoute,
  DemoCrmSystemRoute: DemoCrmSystemRoute,
  DemoCrmIndexRoute: DemoCrmIndexRoute,
  DemoCrmObjectDefIdRecordIdRoute: DemoCrmObjectDefIdRecordIdRoute,
}

const DemoCrmRouteRouteWithChildren = DemoCrmRouteRoute._addFileChildren(
  DemoCrmRouteRouteChildren,
)

interface DemoDocumentEngineRouteRouteChildren {
  DemoDocumentEngineGenerateRoute: typeof DemoDocumentEngineGenerateRoute
  DemoDocumentEngineGroupsRoute: typeof DemoDocumentEngineGroupsRoute
  DemoDocumentEngineLibraryRoute: typeof DemoDocumentEngineLibraryRoute
  DemoDocumentEngineTemplatesRoute: typeof DemoDocumentEngineTemplatesRoute
  DemoDocumentEngineVariablesRoute: typeof DemoDocumentEngineVariablesRoute
  DemoDocumentEngineIndexRoute: typeof DemoDocumentEngineIndexRoute
  DemoDocumentEngineDesignerTemplateIdRoute: typeof DemoDocumentEngineDesignerTemplateIdRoute
}

const DemoDocumentEngineRouteRouteChildren: DemoDocumentEngineRouteRouteChildren =
  {
    DemoDocumentEngineGenerateRoute: DemoDocumentEngineGenerateRoute,
    DemoDocumentEngineGroupsRoute: DemoDocumentEngineGroupsRoute,
    DemoDocumentEngineLibraryRoute: DemoDocumentEngineLibraryRoute,
    DemoDocumentEngineTemplatesRoute: DemoDocumentEngineTemplatesRoute,
    DemoDocumentEngineVariablesRoute: DemoDocumentEngineVariablesRoute,
    DemoDocumentEngineIndexRoute: DemoDocumentEngineIndexRoute,
    DemoDocumentEngineDesignerTemplateIdRoute:
      DemoDocumentEngineDesignerTemplateIdRoute,
  }

const DemoDocumentEngineRouteRouteWithChildren =
  DemoDocumentEngineRouteRoute._addFileChildren(
    DemoDocumentEngineRouteRouteChildren,
  )

interface DemoGovernedTransitionsRouteRouteChildren {
  DemoGovernedTransitionsJournalRoute: typeof DemoGovernedTransitionsJournalRoute
  DemoGovernedTransitionsMachineRoute: typeof DemoGovernedTransitionsMachineRoute
  DemoGovernedTransitionsIndexRoute: typeof DemoGovernedTransitionsIndexRoute
}

const DemoGovernedTransitionsRouteRouteChildren: DemoGovernedTransitionsRouteRouteChildren =
  {
    DemoGovernedTransitionsJournalRoute: DemoGovernedTransitionsJournalRoute,
    DemoGovernedTransitionsMachineRoute: DemoGovernedTransitionsMachineRoute,
    DemoGovernedTransitionsIndexRoute: DemoGovernedTransitionsIndexRoute,
  }

const DemoGovernedTransitionsRouteRouteWithChildren =
  DemoGovernedTransitionsRouteRoute._addFileChildren(
    DemoGovernedTransitionsRouteRouteChildren,
  )

interface DemoRbacAdminRouteRouteChildren {
  DemoRbacAdminUnderwritingRouteRoute: typeof DemoRbacAdminUnderwritingRouteRoute
}

const DemoRbacAdminRouteRouteChildren: DemoRbacAdminRouteRouteChildren = {
  DemoRbacAdminUnderwritingRouteRoute: DemoRbacAdminUnderwritingRouteRoute,
}

const DemoRbacAdminRouteRouteWithChildren =
  DemoRbacAdminRouteRoute._addFileChildren(DemoRbacAdminRouteRouteChildren)

interface DemoRbacRouteRouteChildren {
  DemoRbacAdminRouteRoute: typeof DemoRbacAdminRouteRouteWithChildren
  DemoRbacBorrowerRouteRoute: typeof DemoRbacBorrowerRouteRoute
  DemoRbacBrokerRouteRoute: typeof DemoRbacBrokerRouteRoute
  DemoRbacLawyerRouteRoute: typeof DemoRbacLawyerRouteRoute
  DemoRbacLenderRouteRoute: typeof DemoRbacLenderRouteRoute
  DemoRbacIndexRoute: typeof DemoRbacIndexRoute
}

const DemoRbacRouteRouteChildren: DemoRbacRouteRouteChildren = {
  DemoRbacAdminRouteRoute: DemoRbacAdminRouteRouteWithChildren,
  DemoRbacBorrowerRouteRoute: DemoRbacBorrowerRouteRoute,
  DemoRbacBrokerRouteRoute: DemoRbacBrokerRouteRoute,
  DemoRbacLawyerRouteRoute: DemoRbacLawyerRouteRoute,
  DemoRbacLenderRouteRoute: DemoRbacLenderRouteRoute,
  DemoRbacIndexRoute: DemoRbacIndexRoute,
}

const DemoRbacRouteRouteWithChildren = DemoRbacRouteRoute._addFileChildren(
  DemoRbacRouteRouteChildren,
)

interface DemoRbacAuthRouteRouteChildren {
  DemoRbacAuthAccessControlRoute: typeof DemoRbacAuthAccessControlRoute
  DemoRbacAuthAuditRoute: typeof DemoRbacAuthAuditRoute
  DemoRbacAuthOnboardingRoute: typeof DemoRbacAuthOnboardingRoute
  DemoRbacAuthRolesRoute: typeof DemoRbacAuthRolesRoute
  DemoRbacAuthIndexRoute: typeof DemoRbacAuthIndexRoute
}

const DemoRbacAuthRouteRouteChildren: DemoRbacAuthRouteRouteChildren = {
  DemoRbacAuthAccessControlRoute: DemoRbacAuthAccessControlRoute,
  DemoRbacAuthAuditRoute: DemoRbacAuthAuditRoute,
  DemoRbacAuthOnboardingRoute: DemoRbacAuthOnboardingRoute,
  DemoRbacAuthRolesRoute: DemoRbacAuthRolesRoute,
  DemoRbacAuthIndexRoute: DemoRbacAuthIndexRoute,
}

const DemoRbacAuthRouteRouteWithChildren =
  DemoRbacAuthRouteRoute._addFileChildren(DemoRbacAuthRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BorrowerRouteRoute: BorrowerRouteRoute,
  BrokerRouteRoute: BrokerRouteRoute,
  LawyerRouteRoute: LawyerRouteRoute,
  LenderRouteRoute: LenderRouteRoute,
  OnboardRouteRoute: OnboardRouteRoute,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  SignUpRoute: SignUpRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DemoAmpsRouteRoute: DemoAmpsRouteRouteWithChildren,
  DemoAuditTraceabilityRouteRoute: DemoAuditTraceabilityRouteRouteWithChildren,
  DemoCrmRouteRoute: DemoCrmRouteRouteWithChildren,
  DemoDocumentEngineRouteRoute: DemoDocumentEngineRouteRouteWithChildren,
  DemoGovernedTransitionsRouteRoute:
    DemoGovernedTransitionsRouteRouteWithChildren,
  DemoRbacRouteRoute: DemoRbacRouteRouteWithChildren,
  DemoRbacAuthRouteRoute: DemoRbacAuthRouteRouteWithChildren,
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoConvexActionCacheRoute: DemoConvexActionCacheRoute,
  DemoConvexAggregateRoute: DemoConvexAggregateRoute,
  DemoConvexApiCredentialsRoute: DemoConvexApiCredentialsRoute,
  DemoConvexAuditLogRoute: DemoConvexAuditLogRoute,
  DemoConvexCascadingDeleteRoute: DemoConvexCascadingDeleteRoute,
  DemoConvexCronsRoute: DemoConvexCronsRoute,
  DemoConvexDebouncerRoute: DemoConvexDebouncerRoute,
  DemoConvexFileManagementRoute: DemoConvexFileManagementRoute,
  DemoConvexFluentRoute: DemoConvexFluentRoute,
  DemoConvexGeospatialRoute: DemoConvexGeospatialRoute,
  DemoConvexLedgerRoute: DemoConvexLedgerRoute,
  DemoConvexMigrationsRoute: DemoConvexMigrationsRoute,
  DemoConvexPresenceRoute: DemoConvexPresenceRoute,
  DemoConvexRateLimiterRoute: DemoConvexRateLimiterRoute,
  DemoConvexTimelineRoute: DemoConvexTimelineRoute,
  DemoConvexTracerRoute: DemoConvexTracerRoute,
  DemoConvexTriggersRoute: DemoConvexTriggersRoute,
  DemoConvexWorkflowRoute: DemoConvexWorkflowRoute,
  DemoListingsRoute: DemoListingsRoute,
  DemoProdLedgerRoute: DemoProdLedgerRoute,
  DemoSimulationRoute: DemoSimulationRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  E2eSwitchOrgRoute: E2eSwitchOrgRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoListingsListingidRoute: DemoListingsListingidRoute,
  DemoListingsIndexRoute: DemoListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
